from __future__ import annotations

import json
import re
import textwrap

from .project_scaffold_names import project_name as scaffold_project_name
from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def node_cli_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = re.sub(r"[^a-z0-9-]+", "-", project_name.lower()).strip("-") or "aegis-node-cli"
    js_title = title.replace("\\", "\\\\").replace("'", "\\'")
    package_json = {
        "name": package_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "description": "A package-free Node.js CLI scaffold generated by Aegis.",
        "bin": {package_name: "./bin/cli.js"},
        "scripts": {
            "start": "node bin/cli.js",
            "test": "node --test tests/commands.test.js",
            "validate": "node build.js",
        },
        "engines": {"node": ">=20"},
    }
    return {
        "package.json": json.dumps(package_json, indent=2) + "\n",
        "bin/cli.js": _strip(
            """
            #!/usr/bin/env node

            import { runCli } from '../src/commands.js';

            const result = runCli(process.argv.slice(2));

            if (result.stdout) {
              console.log(result.stdout);
            }

            if (result.stderr) {
              console.error(result.stderr);
            }

            process.exitCode = result.exitCode;
            """
        ),
        "src/commands.js": _strip(
            """
            export const APP_TITLE = '__TITLE__';

            export function parseArgs(args) {
              const options = {
                name: 'Aegis',
                repeat: 1,
                uppercase: false,
                json: false
              };

              for (let index = 0; index < args.length; index += 1) {
                const token = args[index];
                if (token === '--name') {
                  options.name = readValue(args, index, token);
                  index += 1;
                } else if (token === '--repeat') {
                  const raw = readValue(args, index, token);
                  const repeat = Number.parseInt(raw, 10);
                  if (!Number.isInteger(repeat) || repeat < 1 || repeat > 25) {
                    throw new Error('--repeat must be an integer from 1 to 25.');
                  }
                  options.repeat = repeat;
                  index += 1;
                } else if (token === '--uppercase') {
                  options.uppercase = true;
                } else if (token === '--json') {
                  options.json = true;
                } else if (token === '--help' || token === '-h') {
                  options.help = true;
                } else {
                  throw new Error('Unknown argument: ' + token);
                }
              }

              if (!options.name.trim()) {
                throw new Error('--name cannot be empty.');
              }

              return options;
            }

            export function buildLines(options) {
              const lines = [];
              for (let index = 1; index <= options.repeat; index += 1) {
                const text = APP_TITLE + ' ready for ' + options.name + ' (' + index + '/' + options.repeat + ')';
                lines.push(options.uppercase ? text.toUpperCase() : text);
              }
              return lines;
            }

            export function runCli(args) {
              try {
                const options = parseArgs(args);
                if (options.help) {
                  return {
                    exitCode: 0,
                    stdout: usage(),
                    stderr: ''
                  };
                }

                const lines = buildLines(options);
                return {
                  exitCode: 0,
                  stdout: options.json
                    ? JSON.stringify({ app: APP_TITLE, lines }, null, 2)
                    : lines.join('\\n'),
                  stderr: ''
                };
              } catch (error) {
                return {
                  exitCode: 2,
                  stdout: '',
                  stderr: error.message + '\\n\\n' + usage()
                };
              }
            }

            function readValue(args, index, option) {
              if (index + 1 >= args.length) {
                throw new Error(option + ' requires a value.');
              }
              return args[index + 1];
            }

            function usage() {
              return [
                APP_TITLE,
                '',
                'Usage:',
                '  node bin/cli.js [--name VALUE] [--repeat 1-25] [--uppercase] [--json]',
                '',
                'Examples:',
                '  node bin/cli.js --name Aegis --repeat 2',
                '  node bin/cli.js --json'
              ].join('\\n');
            }
            """
        ).replace("__TITLE__", js_title),
        "tests/commands.test.js": _strip(
            """
            import test from 'node:test';
            import assert from 'node:assert/strict';

            import { buildLines, parseArgs, runCli } from '../src/commands.js';

            test('parseArgs reads name, repeat, and flags', () => {
              const options = parseArgs(['--name', 'Mercy', '--repeat', '2', '--uppercase']);
              assert.equal(options.name, 'Mercy');
              assert.equal(options.repeat, 2);
              assert.equal(options.uppercase, true);
            });

            test('buildLines creates repeatable output', () => {
              const lines = buildLines({ name: 'Aegis', repeat: 2, uppercase: false });
              assert.equal(lines.length, 2);
              assert.match(lines[0], /Aegis/);
            });

            test('runCli returns an error for invalid repeat values', () => {
              const result = runCli(['--repeat', '0']);
              assert.equal(result.exitCode, 2);
              assert.match(result.stderr, /--repeat/);
            });
            """
        ),
        "build.js": _strip(
            """
            import { spawnSync } from 'node:child_process';
            import { existsSync } from 'node:fs';

            const requiredFiles = [
              'package.json',
              'bin/cli.js',
              'src/commands.js',
              'tests/commands.test.js'
            ];

            for (const file of requiredFiles) {
              if (!existsSync(file)) {
                console.error('Missing required file:', file);
                process.exit(1);
              }
            }

            const commands = [
              ['node', ['--check', 'bin/cli.js']],
              ['node', ['--check', 'src/commands.js']],
              ['node', ['--test', 'tests/commands.test.js']],
              ['node', ['bin/cli.js', '--name', 'Validation', '--repeat', '2']]
            ];

            for (const [command, args] of commands) {
              console.log('Running:', command, ...args);
              const completed = spawnSync(command, args, {
                stdio: 'inherit'
              });
              if (completed.status !== 0) {
                process.exit(completed.status ?? 1);
              }
            }

            console.log('Node.js CLI scaffold passed validation.');
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            coverage
            dist
            *.log
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Node.js CLI scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            node build.js
            ```

            ## Run

            ```powershell
            node bin/cli.js --name Aegis --repeat 2
            node bin/cli.js --json
            ```

            The package also exposes a bin entry in `package.json` for later packaging or `npm link` workflows.
            """
        ),
    }


def node_http_api_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = re.sub(r"[^a-z0-9-]+", "-", project_name.lower()).strip("-") or "aegis-node-api"
    package_json = {
        "name": package_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "description": "Dependency-free Node.js HTTP API scaffold generated by Aegis.",
        "scripts": {
            "start": "node src/server.js",
            "test": "node --test tests/api.test.js",
            "validate": "node build.js",
        },
        "engines": {"node": ">=20"},
    }
    return {
        "package.json": json.dumps(package_json, indent=2) + "\n",
        "src/store.js": _strip(
            """
            export function createItemStore(initialItems = []) {
              let nextId = 1;
              const items = new Map();

              for (const item of initialItems) {
                const id = String(item.id ?? nextId++);
                items.set(id, {
                  id,
                  name: String(item.name ?? 'Untitled item'),
                  status: String(item.status ?? 'active'),
                  createdAt: item.createdAt ?? new Date().toISOString()
                });
              }

              return {
                list() {
                  return [...items.values()];
                },
                find(id) {
                  return items.get(String(id)) ?? null;
                },
                create(payload) {
                  const name = String(payload?.name ?? '').trim();
                  if (!name) {
                    throw new Error('name is required');
                  }
                  const id = String(nextId++);
                  const item = {
                    id,
                    name,
                    status: String(payload?.status ?? 'active'),
                    createdAt: new Date().toISOString()
                  };
                  items.set(id, item);
                  return item;
                }
              };
            }
            """
        ),
        "src/server.js": _strip(
            """
            import { createServer } from 'node:http';
            import { pathToFileURL } from 'node:url';

            import { createItemStore } from './store.js';

            const defaultStore = createItemStore([
              { id: 'seed-1', name: 'First API item', status: 'active' }
            ]);

            export function createApiServer({ store = defaultStore } = {}) {
              return createServer(async (request, response) => {
                const url = new URL(request.url ?? '/', 'http://localhost');
                const method = request.method ?? 'GET';

                try {
                  if (method === 'GET' && url.pathname === '/health') {
                    return sendJson(response, 200, {
                      ok: true,
                      service: 'aegis-node-api',
                      timestamp: new Date().toISOString()
                    });
                  }

                  if (method === 'GET' && url.pathname === '/api/items') {
                    return sendJson(response, 200, { items: store.list() });
                  }

                  if (method === 'POST' && url.pathname === '/api/items') {
                    const payload = await readJson(request);
                    const item = store.create(payload);
                    return sendJson(response, 201, { item });
                  }

                  const itemMatch = url.pathname.match(/^\\/api\\/items\\/([^/]+)$/);
                  if (method === 'GET' && itemMatch) {
                    const item = store.find(itemMatch[1]);
                    if (!item) {
                      return sendJson(response, 404, { error: 'item not found' });
                    }
                    return sendJson(response, 200, { item });
                  }

                  return sendJson(response, 404, { error: 'route not found' });
                } catch (error) {
                  return sendJson(response, 400, { error: error.message });
                }
              });
            }

            async function readJson(request) {
              const chunks = [];
              let size = 0;

              for await (const chunk of request) {
                size += chunk.length;
                if (size > 1_000_000) {
                  throw new Error('request body is too large');
                }
                chunks.push(chunk);
              }

              const body = Buffer.concat(chunks).toString('utf8').trim();
              if (!body) {
                return {};
              }

              try {
                return JSON.parse(body);
              } catch {
                throw new Error('request body must be valid JSON');
              }
            }

            function sendJson(response, statusCode, payload) {
              const body = JSON.stringify(payload, null, 2);
              response.writeHead(statusCode, {
                'access-control-allow-origin': '*',
                'content-type': 'application/json; charset=utf-8'
              });
              response.end(body);
            }

            if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
              const port = Number.parseInt(process.env.PORT || '8788', 10);
              createApiServer().listen(port, '127.0.0.1', () => {
                console.log(`API listening at http://127.0.0.1:${port}`);
              });
            }
            """
        ),
        "tests/api.test.js": _strip(
            """
            import test from 'node:test';
            import assert from 'node:assert/strict';

            import { createApiServer } from '../src/server.js';
            import { createItemStore } from '../src/store.js';

            test('health endpoint returns service status', async () => {
              const fixture = await startServer();
              try {
                const response = await fetch(`${fixture.baseUrl}/health`);
                const payload = await response.json();
                assert.equal(response.status, 200);
                assert.equal(payload.ok, true);
              } finally {
                await fixture.close();
              }
            });

            test('item routes list, create, and fetch records', async () => {
              const fixture = await startServer();
              try {
                const listResponse = await fetch(`${fixture.baseUrl}/api/items`);
                const listPayload = await listResponse.json();
                assert.equal(listResponse.status, 200);
                assert.equal(listPayload.items.length, 1);

                const createResponse = await fetch(`${fixture.baseUrl}/api/items`, {
                  method: 'POST',
                  headers: { 'content-type': 'application/json' },
                  body: JSON.stringify({ name: 'Generated item', status: 'queued' })
                });
                const createPayload = await createResponse.json();
                assert.equal(createResponse.status, 201);
                assert.equal(createPayload.item.name, 'Generated item');

                const getResponse = await fetch(`${fixture.baseUrl}/api/items/${createPayload.item.id}`);
                const getPayload = await getResponse.json();
                assert.equal(getResponse.status, 200);
                assert.equal(getPayload.item.status, 'queued');
              } finally {
                await fixture.close();
              }
            });

            test('invalid JSON returns a client error', async () => {
              const fixture = await startServer();
              try {
                const response = await fetch(`${fixture.baseUrl}/api/items`, {
                  method: 'POST',
                  headers: { 'content-type': 'application/json' },
                  body: '{not json'
                });
                const payload = await response.json();
                assert.equal(response.status, 400);
                assert.match(payload.error, /valid JSON/);
              } finally {
                await fixture.close();
              }
            });

            async function startServer() {
              const store = createItemStore([{ id: 'seed', name: 'Seed item', status: 'active' }]);
              const server = createApiServer({ store });
              await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
              const address = server.address();
              return {
                baseUrl: `http://${address.address}:${address.port}`,
                close: () => new Promise((resolve, reject) => {
                  server.close((error) => (error ? reject(error) : resolve()));
                })
              };
            }
            """
        ),
        "build.js": _strip(
            """
            import { spawnSync } from 'node:child_process';
            import { existsSync, readFileSync } from 'node:fs';

            const requiredFiles = [
              'package.json',
              'src/server.js',
              'src/store.js',
              'tests/api.test.js'
            ];

            for (const file of requiredFiles) {
              if (!existsSync(file)) {
                console.error('Missing required file:', file);
                process.exit(1);
              }
            }

            const server = readFileSync('src/server.js', 'utf8');
            for (const marker of ['/health', '/api/items', 'createApiServer', 'readJson']) {
              if (!server.includes(marker)) {
                console.error('src/server.js is missing:', marker);
                process.exit(1);
              }
            }

            const commands = [
              ['node', ['--check', 'src/server.js']],
              ['node', ['--check', 'src/store.js']],
              ['node', ['--test', 'tests/api.test.js']]
            ];

            for (const [command, args] of commands) {
              console.log('Running:', command, ...args);
              const completed = spawnSync(command, args, { stdio: 'inherit' });
              if (completed.status !== 0) {
                process.exit(completed.status ?? 1);
              }
            }

            console.log('Node.js HTTP API scaffold passed validation.');
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            coverage
            dist
            *.log
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Dependency-free Node.js HTTP API scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            node build.js
            ```

            ## Run

            ```powershell
            node src/server.js
            ```

            ## Endpoints

            - `GET /health`
            - `GET /api/items`
            - `POST /api/items`
            - `GET /api/items/:id`
            """
        ),
    }


def node_fullstack_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = re.sub(r"[^a-z0-9-]+", "-", project_name.lower()).strip("-") or "aegis-fullstack-app"
    html_title = (
        title.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
    package_json = {
        "name": package_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "description": "Dependency-free full-stack app scaffold generated by Aegis.",
        "scripts": {
            "start": "node src/server.js",
            "test": "node --test tests/fullstack.test.js",
            "validate": "node build.js",
        },
        "engines": {"node": ">=20"},
    }
    return {
        "package.json": json.dumps(package_json, indent=2) + "\n",
        "public/index.html": _strip(
            f"""
            <!doctype html>
            <html lang="en">
              <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="description" content="{html_title} full-stack app generated by Aegis." />
                <title>{html_title}</title>
                <link rel="stylesheet" href="/styles.css" />
              </head>
              <body>
                <main class="app-shell">
                  <header class="hero">
                    <div>
                      <p class="eyebrow">Full-stack workspace</p>
                      <h1>{html_title}</h1>
                      <p class="lead">A no-install app starter with a static frontend, JSON-backed API, task workflow, and validation tests.</p>
                    </div>
                    <section class="status-panel" aria-label="Project status">
                      <span>Local API</span>
                      <strong data-health>Checking...</strong>
                      <p>Backed by Node.js stdlib HTTP and a JSON data file.</p>
                    </section>
                  </header>

                  <section class="workspace-grid">
                    <form class="task-form" data-task-form>
                      <div>
                        <p class="eyebrow">Create</p>
                        <h2>Add a work item</h2>
                      </div>
                      <label>
                        Title
                        <input name="title" type="text" placeholder="Design customer dashboard" required />
                      </label>
                      <label>
                        Priority
                        <select name="priority">
                          <option>High</option>
                          <option selected>Medium</option>
                          <option>Low</option>
                        </select>
                      </label>
                      <button type="submit">Add task</button>
                      <p class="form-status" data-status role="status" aria-live="polite"></p>
                    </form>

                    <section class="task-board" aria-labelledby="task-board-title">
                      <div class="board-header">
                        <div>
                          <p class="eyebrow">Dashboard</p>
                          <h2 id="task-board-title">Active tasks</h2>
                        </div>
                        <button data-refresh type="button">Refresh</button>
                      </div>
                      <div class="task-list" data-task-list></div>
                    </section>
                  </section>
                </main>
                <script src="/app.js"></script>
              </body>
            </html>
            """
        ),
        "public/styles.css": _strip(
            """
            :root {
              color-scheme: dark;
              --bg: #071018;
              --panel: #0f1b25;
              --panel-strong: #142331;
              --text: #eef6ff;
              --muted: #aab8c6;
              --accent: #36e08a;
              --warning: #f4c55f;
              --border: rgba(255, 255, 255, 0.12);
              font-family: Arial, Helvetica, sans-serif;
            }

            * {
              box-sizing: border-box;
            }

            body {
              min-width: 320px;
              min-height: 100vh;
              margin: 0;
              background:
                linear-gradient(135deg, rgba(54, 224, 138, 0.12), transparent 32%),
                linear-gradient(180deg, #08141d 0%, #04080d 100%);
              color: var(--text);
            }

            button,
            input,
            select {
              font: inherit;
            }

            button {
              min-height: 42px;
              border: 0;
              border-radius: 8px;
              background: var(--accent);
              color: #04120b;
              cursor: pointer;
              font-weight: 800;
              padding: 0 16px;
            }

            button.secondary,
            [data-refresh] {
              border: 1px solid var(--border);
              background: rgba(255, 255, 255, 0.05);
              color: var(--text);
            }

            .app-shell {
              width: min(1180px, calc(100vw - 32px));
              margin: 0 auto;
              padding: 36px 0;
            }

            .hero {
              display: grid;
              grid-template-columns: minmax(0, 1fr) 330px;
              gap: 18px;
              align-items: stretch;
              border-bottom: 1px solid var(--border);
              padding-bottom: 28px;
            }

            .eyebrow {
              margin: 0 0 10px;
              color: var(--accent);
              font-size: 12px;
              font-weight: 800;
              text-transform: uppercase;
            }

            h1,
            h2,
            p {
              margin-top: 0;
            }

            h1 {
              max-width: 780px;
              margin-bottom: 14px;
              font-size: clamp(42px, 7vw, 82px);
              line-height: 1;
              letter-spacing: 0;
            }

            h2 {
              margin-bottom: 0;
              font-size: 26px;
              letter-spacing: 0;
            }

            .lead,
            .status-panel p,
            .form-status,
            .task-meta {
              color: var(--muted);
              line-height: 1.55;
            }

            .status-panel,
            .task-form,
            .task-board,
            .task-card {
              border: 1px solid var(--border);
              border-radius: 8px;
              background: rgba(255, 255, 255, 0.045);
            }

            .status-panel {
              padding: 20px;
            }

            .status-panel span,
            .status-panel strong {
              display: block;
            }

            .status-panel strong {
              margin: 10px 0;
              color: var(--warning);
              font-size: 24px;
            }

            .workspace-grid {
              display: grid;
              grid-template-columns: 360px minmax(0, 1fr);
              gap: 18px;
              padding-top: 24px;
            }

            .task-form,
            .task-board {
              padding: 18px;
            }

            .task-form {
              align-self: start;
              display: grid;
              gap: 14px;
            }

            label {
              display: grid;
              gap: 8px;
              color: var(--muted);
              font-size: 14px;
            }

            input,
            select {
              min-height: 42px;
              border: 1px solid var(--border);
              border-radius: 8px;
              background: var(--panel);
              color: var(--text);
              padding: 0 12px;
            }

            .board-header,
            .task-card {
              display: flex;
              align-items: center;
              justify-content: space-between;
              gap: 14px;
            }

            .task-list {
              display: grid;
              gap: 12px;
              margin-top: 18px;
            }

            .task-card {
              background: var(--panel-strong);
              padding: 14px;
            }

            .task-card h3 {
              margin: 0 0 6px;
              font-size: 18px;
            }

            .task-actions {
              display: flex;
              gap: 8px;
              flex-wrap: wrap;
            }

            .empty-state {
              border: 1px dashed var(--border);
              border-radius: 8px;
              color: var(--muted);
              padding: 24px;
              text-align: center;
            }

            @media (max-width: 860px) {
              .hero,
              .workspace-grid {
                grid-template-columns: 1fr;
              }

              .board-header,
              .task-card {
                align-items: flex-start;
                flex-direction: column;
              }
            }
            """
        ),
        "public/app.js": _strip(
            """
            const healthEl = document.querySelector('[data-health]');
            const form = document.querySelector('[data-task-form]');
            const statusEl = document.querySelector('[data-status]');
            const listEl = document.querySelector('[data-task-list]');
            const refreshButton = document.querySelector('[data-refresh]');

            async function requestJson(path, options = {}) {
              const response = await fetch(path, {
                ...options,
                headers: {
                  'content-type': 'application/json',
                  ...(options.headers || {})
                }
              });
              const payload = await response.json();
              if (!response.ok) {
                throw new Error(payload.error || 'Request failed');
              }
              return payload;
            }

            function renderTasks(tasks) {
              if (!tasks.length) {
                listEl.innerHTML = '<div class="empty-state">No tasks yet. Add the first item to begin.</div>';
                return;
              }

              listEl.innerHTML = tasks.map((task) => `
                <article class="task-card">
                  <div>
                    <h3>${escapeHtml(task.title)}</h3>
                    <p class="task-meta">${escapeHtml(task.priority)} priority · ${escapeHtml(task.status)}</p>
                  </div>
                  <div class="task-actions">
                    <button class="secondary" data-complete="${task.id}" type="button">Complete</button>
                    <button class="secondary" data-delete="${task.id}" type="button">Delete</button>
                  </div>
                </article>
              `).join('');
            }

            async function loadTasks() {
              const payload = await requestJson('/api/tasks');
              renderTasks(payload.tasks);
            }

            async function checkHealth() {
              try {
                const payload = await requestJson('/api/health');
                healthEl.textContent = payload.ok ? 'Online' : 'Needs attention';
              } catch {
                healthEl.textContent = 'Offline';
              }
            }

            form?.addEventListener('submit', async (event) => {
              event.preventDefault();
              const data = new FormData(form);
              try {
                await requestJson('/api/tasks', {
                  method: 'POST',
                  body: JSON.stringify({
                    title: data.get('title'),
                    priority: data.get('priority')
                  })
                });
                statusEl.textContent = 'Task added.';
                form.reset();
                await loadTasks();
              } catch (error) {
                statusEl.textContent = error.message;
              }
            });

            listEl?.addEventListener('click', async (event) => {
              const button = event.target.closest('button');
              if (!button) {
                return;
              }

              try {
                if (button.dataset.complete) {
                  await requestJson(`/api/tasks/${button.dataset.complete}`, {
                    method: 'PATCH',
                    body: JSON.stringify({ status: 'complete' })
                  });
                }
                if (button.dataset.delete) {
                  await requestJson(`/api/tasks/${button.dataset.delete}`, { method: 'DELETE' });
                }
                await loadTasks();
              } catch (error) {
                statusEl.textContent = error.message;
              }
            });

            refreshButton?.addEventListener('click', loadTasks);

            function escapeHtml(value) {
              return String(value)
                .replaceAll('&', '&amp;')
                .replaceAll('<', '&lt;')
                .replaceAll('>', '&gt;')
                .replaceAll('"', '&quot;')
                .replaceAll("'", '&#039;');
            }

            checkHealth();
            loadTasks().catch((error) => {
              statusEl.textContent = error.message;
            });
            """
        ),
        "src/store.js": _strip(
            """
            import { randomUUID } from 'node:crypto';
            import { mkdir, readFile, writeFile } from 'node:fs/promises';
            import { dirname } from 'node:path';

            const defaultSeed = [
              { id: 'seed-1', title: 'Review generated scaffold', priority: 'High', status: 'active' },
              { id: 'seed-2', title: 'Connect real project data', priority: 'Medium', status: 'active' }
            ];

            export function createJsonStore({ filePath = 'data/tasks.json', seed = defaultSeed } = {}) {
              let loaded = false;
              let state = { tasks: [] };

              async function load() {
                if (loaded) {
                  return;
                }

                try {
                  const payload = JSON.parse(await readFile(filePath, 'utf8'));
                  state = { tasks: Array.isArray(payload.tasks) ? payload.tasks : [] };
                } catch (error) {
                  if (error.code !== 'ENOENT') {
                    throw error;
                  }
                  state = {
                    tasks: seed.map((task) => ({
                      ...task,
                      createdAt: task.createdAt ?? new Date().toISOString()
                    }))
                  };
                  await save();
                }
                loaded = true;
              }

              async function save() {
                await mkdir(dirname(filePath), { recursive: true });
                await writeFile(filePath, JSON.stringify(state, null, 2), 'utf8');
              }

              return {
                async listTasks() {
                  await load();
                  return state.tasks;
                },
                async createTask(payload) {
                  await load();
                  const title = String(payload?.title ?? '').trim();
                  if (!title) {
                    throw new Error('title is required');
                  }
                  const task = {
                    id: randomUUID(),
                    title,
                    priority: normalizePriority(payload?.priority),
                    status: 'active',
                    createdAt: new Date().toISOString()
                  };
                  state.tasks = [task, ...state.tasks];
                  await save();
                  return task;
                },
                async updateTask(id, payload) {
                  await load();
                  const index = state.tasks.findIndex((task) => task.id === id);
                  if (index === -1) {
                    return null;
                  }
                  state.tasks[index] = {
                    ...state.tasks[index],
                    title: payload?.title ? String(payload.title).trim() : state.tasks[index].title,
                    priority: payload?.priority ? normalizePriority(payload.priority) : state.tasks[index].priority,
                    status: payload?.status ? String(payload.status) : state.tasks[index].status,
                    updatedAt: new Date().toISOString()
                  };
                  await save();
                  return state.tasks[index];
                },
                async deleteTask(id) {
                  await load();
                  const before = state.tasks.length;
                  state.tasks = state.tasks.filter((task) => task.id !== id);
                  if (state.tasks.length === before) {
                    return false;
                  }
                  await save();
                  return true;
                }
              };
            }

            function normalizePriority(value) {
              const priority = String(value ?? 'Medium');
              return ['High', 'Medium', 'Low'].includes(priority) ? priority : 'Medium';
            }
            """
        ),
        "src/server.js": _strip(
            """
            import { createServer } from 'node:http';
            import { readFile } from 'node:fs/promises';
            import { extname, join, normalize } from 'node:path';
            import { pathToFileURL } from 'node:url';

            import { createJsonStore } from './store.js';

            const contentTypes = {
              '.html': 'text/html; charset=utf-8',
              '.css': 'text/css; charset=utf-8',
              '.js': 'text/javascript; charset=utf-8',
              '.json': 'application/json; charset=utf-8'
            };

            export function createAppServer({ store = createJsonStore(), publicDir = join(process.cwd(), 'public') } = {}) {
              return createServer(async (request, response) => {
                const url = new URL(request.url ?? '/', 'http://localhost');
                const method = request.method ?? 'GET';

                try {
                  if (url.pathname.startsWith('/api/')) {
                    return await handleApi({ method, url, request, response, store });
                  }

                  if (method !== 'GET') {
                    return sendJson(response, 405, { error: 'method not allowed' });
                  }

                  return await serveStatic(url.pathname, response, publicDir);
                } catch (error) {
                  return sendJson(response, 500, { error: error.message });
                }
              });
            }

            async function handleApi({ method, url, request, response, store }) {
              if (method === 'GET' && url.pathname === '/api/health') {
                return sendJson(response, 200, {
                  ok: true,
                  service: 'aegis-fullstack-app',
                  timestamp: new Date().toISOString()
                });
              }

              if (method === 'GET' && url.pathname === '/api/tasks') {
                return sendJson(response, 200, { tasks: await store.listTasks() });
              }

              if (method === 'POST' && url.pathname === '/api/tasks') {
                const task = await store.createTask(await readJson(request));
                return sendJson(response, 201, { task });
              }

              const taskMatch = url.pathname.match(/^\\/api\\/tasks\\/([^/]+)$/);
              if (taskMatch && method === 'PATCH') {
                const task = await store.updateTask(taskMatch[1], await readJson(request));
                return task
                  ? sendJson(response, 200, { task })
                  : sendJson(response, 404, { error: 'task not found' });
              }

              if (taskMatch && method === 'DELETE') {
                const deleted = await store.deleteTask(taskMatch[1]);
                return deleted
                  ? sendJson(response, 200, { ok: true })
                  : sendJson(response, 404, { error: 'task not found' });
              }

              return sendJson(response, 404, { error: 'route not found' });
            }

            async function serveStatic(pathname, response, publicDir) {
              const normalized = normalize(pathname === '/' ? '/index.html' : pathname).replace(/^[/\\\\]+/, '');
              if (normalized.startsWith('..')) {
                return sendJson(response, 403, { error: 'forbidden' });
              }

              try {
                const filePath = join(publicDir, normalized);
                const data = await readFile(filePath);
                response.writeHead(200, { 'content-type': contentTypes[extname(filePath)] || 'application/octet-stream' });
                response.end(data);
              } catch {
                sendJson(response, 404, { error: 'file not found' });
              }
            }

            async function readJson(request) {
              const chunks = [];
              let size = 0;

              for await (const chunk of request) {
                size += chunk.length;
                if (size > 1_000_000) {
                  throw new Error('request body is too large');
                }
                chunks.push(chunk);
              }

              const body = Buffer.concat(chunks).toString('utf8').trim();
              if (!body) {
                return {};
              }

              try {
                return JSON.parse(body);
              } catch {
                throw new Error('request body must be valid JSON');
              }
            }

            function sendJson(response, statusCode, payload) {
              response.writeHead(statusCode, { 'content-type': 'application/json; charset=utf-8' });
              response.end(JSON.stringify(payload, null, 2));
            }

            if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
              const port = Number.parseInt(process.env.PORT || '8790', 10);
              createAppServer().listen(port, '127.0.0.1', () => {
                console.log(`Full-stack app listening at http://127.0.0.1:${port}`);
              });
            }
            """
        ),
        "tests/fullstack.test.js": _strip(
            """
            import test from 'node:test';
            import assert from 'node:assert/strict';
            import { mkdtemp, rm } from 'node:fs/promises';
            import { tmpdir } from 'node:os';
            import { join } from 'node:path';

            import { createAppServer } from '../src/server.js';
            import { createJsonStore } from '../src/store.js';

            test('serves the frontend shell and health endpoint', async () => {
              const fixture = await startServer();
              try {
                const page = await fetch(`${fixture.baseUrl}/`);
                const html = await page.text();
                assert.equal(page.status, 200);
                assert.match(html, /data-task-form/);

                const health = await fetch(`${fixture.baseUrl}/api/health`);
                const payload = await health.json();
                assert.equal(health.status, 200);
                assert.equal(payload.ok, true);
              } finally {
                await fixture.close();
              }
            });

            test('task API creates, updates, lists, and deletes tasks', async () => {
              const fixture = await startServer();
              try {
                const created = await fetch(`${fixture.baseUrl}/api/tasks`, {
                  method: 'POST',
                  headers: { 'content-type': 'application/json' },
                  body: JSON.stringify({ title: 'Ship validation loop', priority: 'High' })
                });
                const createdPayload = await created.json();
                assert.equal(created.status, 201);
                assert.equal(createdPayload.task.priority, 'High');

                const updated = await fetch(`${fixture.baseUrl}/api/tasks/${createdPayload.task.id}`, {
                  method: 'PATCH',
                  headers: { 'content-type': 'application/json' },
                  body: JSON.stringify({ status: 'complete' })
                });
                const updatedPayload = await updated.json();
                assert.equal(updated.status, 200);
                assert.equal(updatedPayload.task.status, 'complete');

                const listed = await fetch(`${fixture.baseUrl}/api/tasks`);
                const listedPayload = await listed.json();
                assert.equal(listed.status, 200);
                assert.ok(listedPayload.tasks.some((task) => task.id === createdPayload.task.id));

                const deleted = await fetch(`${fixture.baseUrl}/api/tasks/${createdPayload.task.id}`, { method: 'DELETE' });
                const deletedPayload = await deleted.json();
                assert.equal(deleted.status, 200);
                assert.equal(deletedPayload.ok, true);
              } finally {
                await fixture.close();
              }
            });

            async function startServer() {
              const tempDir = await mkdtemp(join(tmpdir(), 'aegis-fullstack-'));
              const store = createJsonStore({ filePath: join(tempDir, 'tasks.json'), seed: [] });
              const server = createAppServer({ store, publicDir: join(process.cwd(), 'public') });
              await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
              const address = server.address();
              return {
                baseUrl: `http://${address.address}:${address.port}`,
                close: async () => {
                  await new Promise((resolve, reject) => {
                    server.close((error) => (error ? reject(error) : resolve()));
                  });
                  await rm(tempDir, { recursive: true, force: true });
                }
              };
            }
            """
        ),
        "build.js": _strip(
            """
            import { spawnSync } from 'node:child_process';
            import { existsSync, readFileSync } from 'node:fs';

            const requiredFiles = [
              'package.json',
              'public/index.html',
              'public/styles.css',
              'public/app.js',
              'src/server.js',
              'src/store.js',
              'tests/fullstack.test.js'
            ];

            for (const file of requiredFiles) {
              if (!existsSync(file)) {
                console.error('Missing required file:', file);
                process.exit(1);
              }
            }

            const html = readFileSync('public/index.html', 'utf8');
            const server = readFileSync('src/server.js', 'utf8');
            const store = readFileSync('src/store.js', 'utf8');

            for (const marker of ['data-task-form', 'data-task-list', '/app.js']) {
              if (!html.includes(marker)) {
                console.error('public/index.html is missing:', marker);
                process.exit(1);
              }
            }

            for (const marker of ['/api/health', '/api/tasks', 'createAppServer', 'serveStatic']) {
              if (!server.includes(marker)) {
                console.error('src/server.js is missing:', marker);
                process.exit(1);
              }
            }

            for (const marker of ['createJsonStore', 'createTask', 'updateTask', 'deleteTask']) {
              if (!store.includes(marker)) {
                console.error('src/store.js is missing:', marker);
                process.exit(1);
              }
            }

            const commands = [
              ['node', ['--check', 'public/app.js']],
              ['node', ['--check', 'src/server.js']],
              ['node', ['--check', 'src/store.js']],
              ['node', ['--test', 'tests/fullstack.test.js']]
            ];

            for (const [command, args] of commands) {
              console.log('Running:', command, ...args);
              const completed = spawnSync(command, args, { stdio: 'inherit' });
              if (completed.status !== 0) {
                process.exit(completed.status ?? 1);
              }
            }

            console.log('Node.js full-stack scaffold passed validation.');
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            data
            coverage
            dist
            *.log
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Dependency-free full-stack app scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            node build.js
            ```

            ## Run

            ```powershell
            node src/server.js
            ```

            Then open `http://127.0.0.1:8790`.

            ## Included Surface

            - Static frontend in `public/`
            - JSON-backed task store in `src/store.js`
            - API routes in `src/server.js`
            - Node test coverage in `tests/fullstack.test.js`
            """
        ),
    }



def express_ts_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = _manifest_package_name(project_name)
    return {
        "package.json": _strip(
            f"""
            {{
              "name": "{package_name}",
              "version": "0.1.0",
              "private": true,
              "type": "module",
              "scripts": {{
                "dev": "tsx watch src/server.ts",
                "build": "tsc -p tsconfig.json",
                "start": "node dist/server.js",
                "typecheck": "tsc -p tsconfig.json --noEmit"
              }},
              "dependencies": {{
                "dotenv": "^16.4.7",
                "express": "^4.21.2"
              }},
              "devDependencies": {{
                "@types/express": "^5.0.0",
                "@types/node": "^22.10.1",
                "tsx": "^4.19.2",
                "typescript": "^5.7.2"
              }}
            }}
            """
        ),
        "tsconfig.json": _strip(
            """
            {
              "compilerOptions": {
                "target": "ES2022",
                "module": "NodeNext",
                "moduleResolution": "NodeNext",
                "strict": true,
                "esModuleInterop": true,
                "skipLibCheck": true,
                "forceConsistentCasingInFileNames": true,
                "outDir": "dist",
                "rootDir": "src"
              },
              "include": ["src/**/*.ts"]
            }
            """
        ),
        "src/config.ts": _strip(
            f"""
            import "dotenv/config";

            export const config = {{
              appName: process.env.APP_NAME ?? "{title}",
              nodeEnv: process.env.NODE_ENV ?? "development",
              port: Number(process.env.PORT ?? 3000)
            }};
            """
        ),
        "src/routes/health.ts": _strip(
            """
            import { Router } from "express";

            import { config } from "../config.js";

            export const healthRouter = Router();

            healthRouter.get("/health", (_request, response) => {
              response.json({
                status: "ok",
                service: config.appName,
                environment: config.nodeEnv
              });
            });
            """
        ),
        "src/server.ts": _strip(
            """
            import express from "express";

            import { config } from "./config.js";
            import { healthRouter } from "./routes/health.js";

            export function createApp() {
              const app = express();

              app.use(express.json({ limit: "1mb" }));
              app.use(healthRouter);
              app.get("/api/status", (_request, response) => {
                response.json({ status: "ready" });
              });

              return app;
            }

            if (process.env.NODE_ENV !== "test") {
              createApp().listen(config.port, () => {
                console.log(`${config.appName} listening on http://127.0.0.1:${config.port}`);
              });
            }
            """
        ),
        ".env.example": _strip(
            f"""
            APP_NAME="{title}"
            NODE_ENV=development
            PORT=3000
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            dist
            .env
            npm-debug.log*
            pnpm-debug.log*
            yarn-debug.log*
            yarn-error.log*
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Express TypeScript API generated by Aegis Project Builder.

            ```bash
            npm install
            npm run dev
            ```

            Validate with:

            ```bash
            npm run build
            ```
            """
        ),
    }


def _manifest_package_name(project_name: str, fallback_prefix: str = "aegis") -> str:
    cleaned = scaffold_project_name(project_name)
    if cleaned[0].isdigit():
        cleaned = f"{fallback_prefix}-{cleaned}"
    return cleaned


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
