from __future__ import annotations

import textwrap

from .project_scaffold_names import project_name as scaffold_project_name
from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def express_ts_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = _manifest_package_name(project_name)
    return {
        "package.json": _strip(
            f"""
            {{
              "name": "{package_name}",
              "version": "0.1.0",
              "private": true,
              "type": "module",
              "scripts": {{
                "dev": "tsx watch src/server.ts",
                "build": "tsc -p tsconfig.json",
                "start": "node dist/server.js",
                "typecheck": "tsc -p tsconfig.json --noEmit"
              }},
              "dependencies": {{
                "dotenv": "^16.4.7",
                "express": "^4.21.2"
              }},
              "devDependencies": {{
                "@types/express": "^5.0.0",
                "@types/node": "^22.10.1",
                "tsx": "^4.19.2",
                "typescript": "^5.7.2"
              }}
            }}
            """
        ),
        "tsconfig.json": _strip(
            """
            {
              "compilerOptions": {
                "target": "ES2022",
                "module": "NodeNext",
                "moduleResolution": "NodeNext",
                "strict": true,
                "esModuleInterop": true,
                "skipLibCheck": true,
                "forceConsistentCasingInFileNames": true,
                "outDir": "dist",
                "rootDir": "src"
              },
              "include": ["src/**/*.ts"]
            }
            """
        ),
        "src/config.ts": _strip(
            f"""
            import "dotenv/config";

            export const config = {{
              appName: process.env.APP_NAME ?? "{title}",
              nodeEnv: process.env.NODE_ENV ?? "development",
              port: Number(process.env.PORT ?? 3000)
            }};
            """
        ),
        "src/routes/health.ts": _strip(
            """
            import { Router } from "express";

            import { config } from "../config.js";

            export const healthRouter = Router();

            healthRouter.get("/health", (_request, response) => {
              response.json({
                status: "ok",
                service: config.appName,
                environment: config.nodeEnv
              });
            });
            """
        ),
        "src/server.ts": _strip(
            """
            import express from "express";

            import { config } from "./config.js";
            import { healthRouter } from "./routes/health.js";

            export function createApp() {
              const app = express();

              app.use(express.json({ limit: "1mb" }));
              app.use(healthRouter);
              app.get("/api/status", (_request, response) => {
                response.json({ status: "ready" });
              });

              return app;
            }

            if (process.env.NODE_ENV !== "test") {
              createApp().listen(config.port, () => {
                console.log(`${config.appName} listening on http://127.0.0.1:${config.port}`);
              });
            }
            """
        ),
        ".env.example": _strip(
            f"""
            APP_NAME="{title}"
            NODE_ENV=development
            PORT=3000
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            dist
            .env
            npm-debug.log*
            pnpm-debug.log*
            yarn-debug.log*
            yarn-error.log*
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Express TypeScript API generated by Aegis Project Builder.

            ```bash
            npm install
            npm run dev
            ```

            Validate with:

            ```bash
            npm run build
            ```
            """
        ),
    }


def _manifest_package_name(project_name: str, fallback_prefix: str = "aegis") -> str:
    cleaned = scaffold_project_name(project_name)
    if cleaned[0].isdigit():
        cleaned = f"{fallback_prefix}-{cleaned}"
    return cleaned


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
