from __future__ import annotations

from .schemas import ProjectScaffoldPreset


def scaffold_presets() -> list[ProjectScaffoldPreset]:
    return [
        ProjectScaffoldPreset(
            id="nextjs-ts-tailwind",
            label="Next.js TypeScript + Tailwind",
            framework="Next.js App Router",
            language="TypeScript",
            package_manager="npm",
            install_command="npm install",
            validation_command="npm run build",
            description="Production-ready web app shell with App Router, Tailwind, typed config, and a polished first screen.",
            tags=["web", "react", "full-stack", "tailwind"],
        ),
        ProjectScaffoldPreset(
            id="vite-react-ts",
            label="Vite React TypeScript",
            framework="Vite + React",
            language="TypeScript",
            package_manager="npm",
            install_command="npm install",
            validation_command="npm run build",
            description="Fast client app scaffold with Vite, React, TypeScript, and a focused dashboard surface.",
            tags=["web", "react", "spa", "vite"],
        ),
        ProjectScaffoldPreset(
            id="static-html-site",
            label="Static HTML Website",
            framework="HTML + CSS + JavaScript",
            language="JavaScript",
            package_manager="browser",
            install_command="",
            validation_command="node build.js",
            description="Dependency-free business website with responsive pages, contact form behavior, local preview server, and static validation.",
            tags=["web", "website", "html", "css", "javascript", "static"],
        ),
        ProjectScaffoldPreset(
            id="browser-extension-mv3",
            label="Browser Extension Manifest V3",
            framework="Chrome/Edge Manifest V3",
            language="JavaScript + HTML + CSS",
            package_manager="browser",
            install_command="",
            validation_command="python build.py",
            description="Package-free browser extension scaffold with MV3 manifest, popup, options page, background service worker, content script, and static validation.",
            tags=["browser", "extension", "chrome", "edge", "mv3"],
        ),
        ProjectScaffoldPreset(
            id="vscode-extension-js",
            label="VS Code Extension JavaScript",
            framework="VS Code Extension API",
            language="JavaScript",
            package_manager="node",
            install_command="",
            validation_command="python build.py",
            description="Package-free VS Code extension scaffold with command contributions, activation events, settings, status bar wiring, and static validation.",
            tags=["vscode", "extension", "javascript", "developer-tools"],
        ),
        ProjectScaffoldPreset(
            id="node-cli-js",
            label="Node.js CLI Tool",
            framework="Node.js",
            language="JavaScript",
            package_manager="node",
            install_command="",
            validation_command="node build.js",
            description="Package-free Node.js command-line tool with argument parsing, executable bin entrypoint, built-in node:test coverage, and static validation.",
            tags=["node", "javascript", "cli", "automation", "tool"],
        ),
        ProjectScaffoldPreset(
            id="node-http-api-js",
            label="Node.js HTTP API",
            framework="Node.js stdlib HTTP",
            language="JavaScript",
            package_manager="node",
            install_command="",
            validation_command="node build.js",
            description="Dependency-free REST API scaffold with health checks, JSON CRUD routes, in-memory storage, node:test coverage, and static validation.",
            tags=["api", "node", "javascript", "backend", "rest"],
        ),
        ProjectScaffoldPreset(
            id="node-fullstack-js",
            label="Node.js Full-Stack App",
            framework="Node.js stdlib HTTP + static frontend",
            language="JavaScript",
            package_manager="node",
            install_command="",
            validation_command="node build.js",
            description="Dependency-free full-stack CRUD app with static UI, JSON persistence, API routes, node:test coverage, and local preview server.",
            tags=["web", "full-stack", "node", "javascript", "crud", "dashboard"],
        ),
        ProjectScaffoldPreset(
            id="powershell-module",
            label="PowerShell Automation Module",
            framework="PowerShell module",
            language="PowerShell",
            package_manager="powershell",
            install_command="",
            validation_command="powershell -NoProfile -ExecutionPolicy Bypass -File ./build.ps1",
            description="Dependency-free PowerShell module scaffold with manifest, exported functions, CLI script, parser validation, and smoke tests.",
            tags=["powershell", "automation", "windows", "module", "scripts"],
        ),
        ProjectScaffoldPreset(
            id="python-cli",
            label="Python CLI Package",
            framework="Python package",
            language="Python",
            package_manager="pip",
            install_command="python -m pip install -e .[dev]",
            validation_command="python build.py",
            description="Installable Python command-line project with pyproject metadata, package source, dependency-free build validation, and smoke tests.",
            tags=["python", "cli", "automation", "tests"],
        ),
        ProjectScaffoldPreset(
            id="python-tkinter-desktop",
            label="Python Tkinter Desktop App",
            framework="Python stdlib Tkinter",
            language="Python",
            package_manager="python",
            install_command="",
            validation_command="python build.py",
            description="Dependency-light desktop utility with a Tkinter GUI, app state layer, JSON persistence, and validation tests.",
            tags=["python", "desktop", "tkinter", "gui", "utility"],
        ),
        ProjectScaffoldPreset(
            id="python-stdlib-api",
            label="Python Stdlib HTTP API",
            framework="Python http.server",
            language="Python",
            package_manager="python",
            install_command="",
            validation_command="python build.py",
            description="Dependency-free Python REST API scaffold with JSON CRUD routes, file-backed storage, unittest coverage, and static compilation checks.",
            tags=["api", "python", "backend", "rest", "json"],
        ),
        ProjectScaffoldPreset(
            id="fastapi-python-api",
            label="FastAPI Python API",
            framework="FastAPI",
            language="Python",
            package_manager="pip",
            install_command="python -m pip install -e .[dev]",
            validation_command="python -m pytest",
            description="Typed FastAPI service with settings, health route, app factory, and API smoke tests.",
            tags=["api", "python", "fastapi", "backend"],
        ),
        ProjectScaffoldPreset(
            id="express-ts-api",
            label="Express TypeScript API",
            framework="Express",
            language="TypeScript",
            package_manager="npm",
            install_command="npm install",
            validation_command="npm run build",
            description="Node/Express API scaffold with TypeScript, config loading, health route, and production build script.",
            tags=["api", "node", "typescript", "backend"],
        ),
        ProjectScaffoldPreset(
            id="sqlite-python-db",
            label="SQLite Python Database Tool",
            framework="SQLite + Python stdlib",
            language="Python",
            package_manager="python",
            install_command="",
            validation_command="python build.py",
            description="Dependency-light database project with SQLite schema, seed data, CLI helpers, query examples, and validation tests.",
            tags=["database", "sqlite", "sql", "python", "cli"],
        ),
        ProjectScaffoldPreset(
            id="cpp-cmake-cli",
            label="C++ CMake CLI",
            framework="CMake",
            language="C++17",
            package_manager="cmake",
            install_command="",
            validation_command="python build.py",
            description="Portable C++17 command-line project with CMake, include/source layout, and a tiny smoke test executable.",
            tags=["cpp", "cmake", "cli", "native"],
        ),
        ProjectScaffoldPreset(
            id="cpp-cmake-dll",
            label="C++ CMake DLL / Shared Library",
            framework="CMake",
            language="C++17",
            package_manager="cmake",
            install_command="",
            validation_command="python build.py",
            description="Portable C++17 shared-library/DLL project with export macros, CMake build files, and a smoke-test executable.",
            tags=["cpp", "cmake", "dll", "shared-library", "native"],
        ),
        ProjectScaffoldPreset(
            id="cpp-imgui-win32-dx11",
            label="C++ Dear ImGui Win32/DX11 Tool",
            framework="CMake + Dear ImGui + Win32 + DirectX 11",
            language="C++20",
            package_manager="cmake",
            install_command="",
            validation_command="python build.py",
            description="Native Dear ImGui desktop tool scaffold for game-dev editors, inspectors, debug panels, and internal tooling.",
            tags=["cpp", "imgui", "dear-imgui", "win32", "directx11", "game-dev", "tools"],
        ),
        ProjectScaffoldPreset(
            id="cpp-game-loop-cmake",
            label="C++ Game Loop Sandbox",
            framework="CMake",
            language="C++20",
            package_manager="cmake",
            install_command="",
            validation_command="python build.py",
            description="Portable C++ game-development sandbox with fixed timestep loop, lightweight world state, asset registry, and smoke tests.",
            tags=["cpp", "game", "game-dev", "engine", "simulation", "cmake"],
        ),
        ProjectScaffoldPreset(
            id="python-game-file-analyzer",
            label="Game File / Asset Analyzer",
            framework="Python stdlib",
            language="Python",
            package_manager="python",
            install_command="",
            validation_command="python build.py",
            description="Dependency-free static analysis toolkit for owned/authorized game files, asset folders, binary headers, strings, entropy, and format reports.",
            tags=["python", "game-files", "asset-pipeline", "reverse-engineering", "binary-analysis", "tools"],
        ),
        ProjectScaffoldPreset(
            id="cpp-msvc-console-sln",
            label="C++ Visual Studio Console Solution",
            framework="Visual Studio / MSBuild",
            language="C++17",
            package_manager="msbuild",
            install_command="",
            validation_command="python build.py",
            description="Windows C++ console application with a Visual Studio solution, vcxproj, and a hello-world entrypoint that waits for Enter before closing.",
            tags=["cpp", "visual-studio", "sln", "console", "native", "windows"],
        ),
        ProjectScaffoldPreset(
            id="cpp-windows-service",
            label="C++ Windows Service",
            framework="CMake + Win32 Service API",
            language="C++17",
            package_manager="cmake",
            install_command="",
            validation_command="python build.py",
            description="Native Windows service scaffold with service entrypoint, console mode, install/uninstall commands, CMake build files, and smoke tests.",
            tags=["windows", "service", "cpp", "cmake", "native", "system"],
        ),
        ProjectScaffoldPreset(
            id="cpp-windows-internals-hooking",
            label="C++ Windows Internals / Hooking Tool",
            framework="CMake + Win32 API + MinHook-style Abstraction",
            language="C++20",
            package_manager="cmake",
            install_command="",
            validation_command="python build.py",
            description="Authorized Windows internals and instrumentation scaffold with process/module inspection, hook-plan modeling, and MinHook-compatible boundaries.",
            tags=["windows", "internals", "cpp", "hooking", "minhook", "instrumentation", "diagnostics"],
        ),
        ProjectScaffoldPreset(
            id="python-sln-refactor-tool",
            label="Visual Studio Solution Merge/Split Tool",
            framework="Python Stdlib + Visual Studio Solution Parser",
            language="Python 3.11",
            package_manager="python",
            install_command="",
            validation_command="python build.py",
            description="Dependency-free tool for inspecting, merging, and splitting Visual Studio .sln/.vcxproj project collections.",
            tags=["visual-studio", "sln", "vcxproj", "solution", "refactor", "python"],
        ),
        ProjectScaffoldPreset(
            id="windows-kernel-driver-controller",
            label="Windows Kernel Driver + Controller",
            framework="Visual Studio / WDK",
            language="C/C++17",
            package_manager="msbuild",
            install_command="",
            validation_command="python build.py",
            description="Windows driver project plus a C++ controller app that communicates through a documented device IOCTL channel.",
            tags=["windows", "kernel", "driver", "wdk", "cpp", "controller"],
        ),
        ProjectScaffoldPreset(
            id="electron-react-ts",
            label="Electron React TypeScript",
            framework="Electron + Vite + React",
            language="TypeScript",
            package_manager="npm",
            install_command="npm install",
            validation_command="npm run build",
            description="Cross-platform desktop shell with Electron main/preload processes, Vite React renderer, and TypeScript build scripts.",
            tags=["desktop", "electron", "react", "typescript"],
        ),
        ProjectScaffoldPreset(
            id="expo-react-native-ts",
            label="Expo React Native TypeScript",
            framework="Expo",
            language="TypeScript",
            package_manager="npm",
            install_command="npm install",
            validation_command="npm run typecheck",
            description="Mobile app starter for iOS, Android, and web using Expo, React Native, typed screens, and app config.",
            tags=["mobile", "expo", "react-native", "typescript"],
        ),
        ProjectScaffoldPreset(
            id="django-python-web",
            label="Django Python Web App",
            framework="Django",
            language="Python",
            package_manager="pip",
            install_command="python -m pip install -r requirements.txt",
            validation_command="python manage.py test",
            description="Django web app with project settings, first app, health view, tests, and SQLite development defaults.",
            tags=["web", "python", "django", "backend"],
        ),
        ProjectScaffoldPreset(
            id="rust-cli",
            label="Rust CLI",
            framework="Cargo",
            language="Rust",
            package_manager="cargo",
            install_command="",
            validation_command="cargo test",
            description="Rust command-line starter with Cargo metadata, library logic, binary entrypoint, and unit tests.",
            tags=["rust", "cli", "native", "automation"],
        ),
        ProjectScaffoldPreset(
            id="go-http-api",
            label="Go HTTP API",
            framework="Go net/http",
            language="Go",
            package_manager="go",
            install_command="go mod tidy",
            validation_command="go test ./...",
            description="Small Go HTTP API service with typed handlers, health route, server wiring, and tests.",
            tags=["api", "go", "backend", "service"],
        ),
        ProjectScaffoldPreset(
            id="dotnet-webapi-csharp",
            label="ASP.NET Core C# Web API",
            framework="ASP.NET Core Minimal API",
            language="C#",
            package_manager="dotnet",
            install_command="dotnet restore",
            validation_command="dotnet test",
            description="C# solution with ASP.NET Core Minimal API project, xUnit tests, health endpoint, and typed app model.",
            tags=["api", "dotnet", "csharp", "backend"],
        ),
        ProjectScaffoldPreset(
            id="dotnet-console-csharp",
            label="C# .NET Console App",
            framework=".NET Console",
            language="C#",
            package_manager="dotnet",
            install_command="dotnet restore",
            validation_command="python build.py",
            description="Package-free C# console/exe project with a typed command engine, self-test mode, and build validation script.",
            tags=["dotnet", "csharp", "console", "cli", "exe"],
        ),
        ProjectScaffoldPreset(
            id="dotnet-wpf-csharp",
            label="C# WPF Desktop App",
            framework=".NET WPF",
            language="C# + XAML",
            package_manager="dotnet",
            install_command="dotnet restore",
            validation_command="python build.py",
            description="Native Windows WPF desktop app with XAML UI, testable state layer, and package-free smoke validation.",
            tags=["dotnet", "csharp", "wpf", "xaml", "desktop", "windows"],
        ),
        ProjectScaffoldPreset(
            id="tauri-react-ts",
            label="Tauri React TypeScript",
            framework="Tauri + Vite + React",
            language="TypeScript + Rust",
            package_manager="npm/cargo",
            install_command="npm install",
            validation_command="npm run build",
            description="Lightweight desktop app shell with Vite React frontend, Tauri Rust host config, and typed build scripts.",
            tags=["desktop", "tauri", "react", "rust"],
        ),
    ]
