from __future__ import annotations

import re
import textwrap

from .project_scaffold_names import project_name as scaffold_project_name
from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def rust_cli_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    crate_name = _python_package_name(project_name)
    package_name = _manifest_package_name(project_name)
    return {
        "Cargo.toml": _strip(
            f"""
            [package]
            name = "{package_name}"
            version = "0.1.0"
            edition = "2021"

            [lib]
            name = "{crate_name}"
            path = "src/lib.rs"

            [[bin]]
            name = "{package_name}"
            path = "src/main.rs"
            """
        ),
        "src/lib.rs": _strip(
            f"""
            pub fn greeting(target: &str) -> String {{
                format!("{title} ready for {{target}}")
            }}

            #[cfg(test)]
            mod tests {{
                use super::greeting;

                #[test]
                fn builds_greeting() {{
                    assert!(greeting("Aegis").contains("Aegis"));
                }}
            }}
            """
        ),
        "src/main.rs": _strip(
            f"""
            use {crate_name}::greeting;

            fn main() {{
                let target = std::env::args().nth(1).unwrap_or_else(|| "Aegis".to_string());
                println!("{{}}", greeting(&target));
            }}
            """
        ),
        ".gitignore": _strip(
            """
            target
            Cargo.lock
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Rust CLI generated by Aegis Project Builder.

            ```bash
            cargo run -- Aegis
            cargo test
            ```
            """
        ),
    }


def go_http_api_template(project_name: str) -> dict[str, str]:
    module_name = f"example.com/{_manifest_package_name(project_name)}"
    title = _title_from_name(project_name)
    return {
        "go.mod": _strip(
            f"""
            module {module_name}

            go 1.22
            """
        ),
        "cmd/server/main.go": _strip(
            f"""
            package main

            import (
                "log"
                "net/http"

                "{module_name}/internal/api"
            )

            func main() {{
                mux := api.NewRouter("{title}")
                log.Println("listening on http://127.0.0.1:8080")
                if err := http.ListenAndServe(":8080", mux); err != nil {{
                    log.Fatal(err)
                }}
            }}
            """
        ),
        "internal/api/router.go": _strip(
            """
            package api

            import (
                "encoding/json"
                "net/http"
            )

            type HealthResponse struct {
                OK  bool   `json:"ok"`
                App string `json:"app"`
            }

            func NewRouter(appName string) http.Handler {
                mux := http.NewServeMux()
                mux.HandleFunc("GET /health", func(w http.ResponseWriter, r *http.Request) {
                    w.Header().Set("Content-Type", "application/json")
                    _ = json.NewEncoder(w).Encode(HealthResponse{OK: true, App: appName})
                })
                return mux
            }
            """
        ),
        "internal/api/router_test.go": _strip(
            """
            package api

            import (
                "net/http"
                "net/http/httptest"
                "testing"
            )

            func TestHealth(t *testing.T) {
                request := httptest.NewRequest(http.MethodGet, "/health", nil)
                recorder := httptest.NewRecorder()

                NewRouter("Aegis").ServeHTTP(recorder, request)

                if recorder.Code != http.StatusOK {
                    t.Fatalf("expected 200, got %d", recorder.Code)
                }
            }
            """
        ),
        ".gitignore": _strip(
            """
            bin
            coverage.out
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Go HTTP API generated by Aegis Project Builder.

            ```bash
            go mod tidy
            go run ./cmd/server
            go test ./...
            ```
            """
        ),
    }


def _python_package_name(project_name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", project_name.replace("-", "_")).strip("_").lower()
    if not cleaned:
        return "aegis_app"
    if cleaned[0].isdigit():
        cleaned = f"app_{cleaned}"
    return cleaned


def _manifest_package_name(project_name: str, fallback_prefix: str = "aegis") -> str:
    cleaned = scaffold_project_name(project_name)
    if cleaned[0].isdigit():
        cleaned = f"{fallback_prefix}-{cleaned}"
    return cleaned


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
