from __future__ import annotations

import re
import textwrap
import uuid

from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def powershell_module_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    module_name = "".join(word[:1].upper() + word[1:] for word in re.split(r"[-_\s]+", project_name) if word)
    module_name = re.sub(r"[^A-Za-z0-9]", "", module_name) or "AegisAutomation"
    if not re.match(r"^[A-Za-z]", module_name):
        module_name = f"Aegis{module_name}"
    module_guid = str(uuid.uuid4())
    return {
        f"src/{module_name}.psm1": _strip(
            """
            Set-StrictMode -Version Latest

            function Write-AegisLog {
                [CmdletBinding()]
                param(
                    [Parameter(Mandatory = $true)]
                    [ValidateNotNullOrEmpty()]
                    [string]$Message,

                    [ValidateSet('Info', 'Warning', 'Error')]
                    [string]$Level = 'Info'
                )

                $entry = [pscustomobject]@{
                    Timestamp = (Get-Date).ToUniversalTime().ToString('o')
                    Level = $Level
                    Message = $Message
                }
                Write-Host ('[{0}] {1}' -f $entry.Level, $entry.Message)
                return $entry
            }

            function Get-AegisSystemSummary {
                [CmdletBinding()]
                param(
                    [string]$Path = (Get-Location).Path
                )

                $resolvedPath = $Path
                if (Test-Path -LiteralPath $Path) {
                    $resolvedPath = (Resolve-Path -LiteralPath $Path).Path
                }

                return [pscustomobject]@{
                    ComputerName = $env:COMPUTERNAME
                    UserName = $env:USERNAME
                    PowerShellVersion = $PSVersionTable.PSVersion.ToString()
                    TargetPath = $resolvedPath
                    Timestamp = (Get-Date).ToUniversalTime().ToString('o')
                }
            }

            function Test-AegisPath {
                [CmdletBinding()]
                param(
                    [Parameter(Mandatory = $true)]
                    [ValidateNotNullOrEmpty()]
                    [string]$Path,

                    [switch]$Create
                )

                $exists = Test-Path -LiteralPath $Path
                if (-not $exists -and $Create) {
                    [void](New-Item -ItemType Directory -Path $Path -Force)
                    $exists = $true
                }

                return [pscustomobject]@{
                    Path = $Path
                    Exists = $exists
                    Created = [bool]($Create -and $exists)
                }
            }

            Export-ModuleMember -Function Write-AegisLog, Get-AegisSystemSummary, Test-AegisPath
            """
        ),
        f"src/{module_name}.psd1": _strip(
            """
            @{
                RootModule = '__MODULE__.psm1'
                ModuleVersion = '0.1.0'
                GUID = '__GUID__'
                Author = 'Aegis Project Builder'
                CompanyName = 'Aegis'
                Copyright = '(c) Aegis. All rights reserved.'
                Description = 'Dependency-free PowerShell automation module generated by Aegis.'
                PowerShellVersion = '5.1'
                FunctionsToExport = @('Write-AegisLog', 'Get-AegisSystemSummary', 'Test-AegisPath')
                CmdletsToExport = @()
                VariablesToExport = @()
                AliasesToExport = @()
            }
            """
        ).replace("__MODULE__", module_name).replace("__GUID__", module_guid),
        f"scripts/Invoke-{module_name}.ps1": _strip(
            r"""
            [CmdletBinding()]
            param(
                [string]$Path = (Get-Location).Path,
                [switch]$EnsurePath
            )

            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version Latest

            $manifestPath = Join-Path $PSScriptRoot '..\src\__MODULE__.psd1'
            Import-Module $manifestPath -Force

            if ($EnsurePath) {
                Test-AegisPath -Path $Path -Create | Format-List | Out-String | Write-Host
            }

            $summary = Get-AegisSystemSummary -Path $Path
            Write-AegisLog -Message ('Loaded __MODULE__ for {0}' -f $summary.TargetPath) -Level Info | Out-Null
            $summary | ConvertTo-Json -Depth 4
            """
        ).replace("__MODULE__", module_name),
        "tests/Smoke.Tests.ps1": _strip(
            r"""
            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version Latest

            $moduleRoot = Join-Path $PSScriptRoot '..\src'
            $manifestPath = Join-Path $moduleRoot '__MODULE__.psd1'
            Test-ModuleManifest -Path $manifestPath | Out-Null
            Import-Module $manifestPath -Force

            $requiredCommands = @(
                'Write-AegisLog',
                'Get-AegisSystemSummary',
                'Test-AegisPath'
            )
            foreach ($commandName in $requiredCommands) {
                if (-not (Get-Command -Name $commandName -ErrorAction SilentlyContinue)) {
                    throw ('Missing exported command: {0}' -f $commandName)
                }
            }

            $summary = Get-AegisSystemSummary -Path $PSScriptRoot
            if (-not $summary.PowerShellVersion) {
                throw 'Expected PowerShell version in system summary.'
            }

            $tempPath = Join-Path ([System.IO.Path]::GetTempPath()) ('aegis-module-' + [guid]::NewGuid().ToString('N'))
            $pathResult = Test-AegisPath -Path $tempPath -Create
            try {
                if (-not $pathResult.Exists) {
                    throw 'Expected Test-AegisPath to create the requested directory.'
                }
            }
            finally {
                if (Test-Path -LiteralPath $tempPath) {
                    Remove-Item -LiteralPath $tempPath -Recurse -Force
                }
            }

            $logEntry = Write-AegisLog -Message 'smoke' -Level Info
            if ($logEntry.Message -ne 'smoke') {
                throw 'Expected Write-AegisLog to return the logged message.'
            }

            Write-Host 'PowerShell module smoke tests passed.'
            """
        ).replace("__MODULE__", module_name),
        "build.ps1": _strip(
            r"""
            [CmdletBinding()]
            param()

            $ErrorActionPreference = 'Stop'
            Set-StrictMode -Version Latest

            $root = Split-Path -Parent $MyInvocation.MyCommand.Path
            $requiredFiles = @(
                'src\__MODULE__.psm1',
                'src\__MODULE__.psd1',
                'scripts\Invoke-__MODULE__.ps1',
                'tests\Smoke.Tests.ps1'
            )

            foreach ($relativePath in $requiredFiles) {
                $path = Join-Path $root $relativePath
                if (-not (Test-Path -LiteralPath $path)) {
                    throw ('Missing required file: {0}' -f $relativePath)
                }
            }

            foreach ($relativePath in $requiredFiles) {
                $path = Join-Path $root $relativePath
                $content = Get-Content -LiteralPath $path -Raw
                $parseErrors = $null
                [void][System.Management.Automation.PSParser]::Tokenize($content, [ref]$parseErrors)
                if ($parseErrors -and $parseErrors.Count -gt 0) {
                    $details = ($parseErrors | ForEach-Object { '{0}:{1} {2}' -f $_.Token.StartLine, $_.Token.StartColumn, $_.Message }) -join [Environment]::NewLine
                    throw ('PowerShell parser errors in {0}:{1}{2}' -f $relativePath, [Environment]::NewLine, $details)
                }
            }

            $manifestPath = Join-Path $root 'src\__MODULE__.psd1'
            Test-ModuleManifest -Path $manifestPath | Out-Null
            & (Join-Path $root 'tests\Smoke.Tests.ps1')

            Write-Host 'PowerShell module scaffold passed validation.'
            """
        ).replace("__MODULE__", module_name),
        ".gitignore": _strip(
            """
            *.log
            *.tmp
            .env
            .vscode
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Dependency-free PowerShell automation module scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            powershell -NoProfile -ExecutionPolicy Bypass -File .\\build.ps1
            ```

            ## Run

            ```powershell
            powershell -NoProfile -ExecutionPolicy Bypass -File .\\scripts\\Invoke-{module_name}.ps1 -Path . -EnsurePath
            ```

            ## Exports

            - `Write-AegisLog`
            - `Get-AegisSystemSummary`
            - `Test-AegisPath`
            """
        ),
    }


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
