from __future__ import annotations

import re
import textwrap

from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def dotnet_webapi_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    safe_name = "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]+", project_name) if part) or "AegisApi"
    return {
        f"{safe_name}.sln": _strip(
            f"""
            Microsoft Visual Studio Solution File, Format Version 12.00
            # Visual Studio Version 17
            Project("{{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}}") = "{safe_name}.Api", "src/{safe_name}.Api/{safe_name}.Api.csproj", "{{11111111-1111-1111-1111-111111111111}}"
            EndProject
            Project("{{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}}") = "{safe_name}.Tests", "tests/{safe_name}.Tests/{safe_name}.Tests.csproj", "{{22222222-2222-2222-2222-222222222222}}"
            EndProject
            Global
            EndGlobal
            """
        ),
        f"src/{safe_name}.Api/{safe_name}.Api.csproj": _strip(
            """
            <Project Sdk="Microsoft.NET.Sdk.Web">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
              </PropertyGroup>
            </Project>
            """
        ),
        f"src/{safe_name}.Api/Program.cs": _strip(
            f"""
            var builder = WebApplication.CreateBuilder(args);
            var app = builder.Build();

            app.MapGet("/health", () => Results.Ok(new HealthResponse(true, "{title}")));
            app.MapGet("/", () => Results.Ok(new {{ app = "{title}", status = "ready" }}));

            app.Run();

            public partial class Program {{ }}
            public sealed record HealthResponse(bool Ok, string App);
            """
        ),
        f"tests/{safe_name}.Tests/{safe_name}.Tests.csproj": _strip(
            f"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <TargetFramework>net8.0</TargetFramework>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
                <IsPackable>false</IsPackable>
              </PropertyGroup>
              <ItemGroup>
                <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.11" />
                <PackageReference Include="xunit" Version="2.9.2" />
                <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
              </ItemGroup>
              <ItemGroup>
                <ProjectReference Include="../../src/{safe_name}.Api/{safe_name}.Api.csproj" />
              </ItemGroup>
            </Project>
            """
        ),
        f"tests/{safe_name}.Tests/HealthTests.cs": _strip(
            """
            using System.Net;
            using Microsoft.AspNetCore.Mvc.Testing;
            using Xunit;

            public sealed class HealthTests : IClassFixture<WebApplicationFactory<Program>>
            {
                private readonly WebApplicationFactory<Program> _factory;

                public HealthTests(WebApplicationFactory<Program> factory)
                {
                    _factory = factory;
                }

                [Fact]
                public async Task Health_ReturnsOk()
                {
                    var response = await _factory.CreateClient().GetAsync("/health");
                    Assert.Equal(HttpStatusCode.OK, response.StatusCode);
                }
            }
            """
        ),
        ".gitignore": _strip(
            """
            bin
            obj
            .vs
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            ASP.NET Core Minimal API generated by Aegis Project Builder.

            ```bash
            dotnet restore
            dotnet run --project src/{safe_name}.Api
            dotnet test
            ```
            """
        ),
    }


def dotnet_console_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    safe_name = "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]+", project_name) if part) or "AegisTool"
    cs_title = title.replace("\\", "\\\\").replace('"', '\\"')
    return {
        f"src/{safe_name}/{safe_name}.csproj": _strip(
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net8.0</TargetFramework>
                <ImplicitUsings>enable</ImplicitUsings>
                <Nullable>enable</Nullable>
                <AssemblyName>$(MSBuildProjectName)</AssemblyName>
              </PropertyGroup>
            </Project>
            """
        ),
        f"src/{safe_name}/Program.cs": _strip(
            f"""
            using {safe_name};

            return ConsoleApp.Run(args);
            """
        ),
        f"src/{safe_name}/ToolEngine.cs": _strip(
            f"""
            namespace {safe_name};

            public sealed record AppOptions(string Name, int Count, bool SelfTest);

            public static class ConsoleApp
            {{
                public static int Run(string[] args)
                {{
                    try
                    {{
                        var options = Parse(args);
                        if (options.SelfTest)
                        {{
                            return RunSelfTest();
                        }}

                        foreach (var line in BuildOutput(options))
                        {{
                            Console.WriteLine(line);
                        }}
                        return 0;
                    }}
                    catch (ArgumentException ex)
                    {{
                        Console.Error.WriteLine(ex.Message);
                        PrintUsage();
                        return 2;
                    }}
                }}

                public static AppOptions Parse(IReadOnlyList<string> args)
                {{
                    var name = "Aegis";
                    var count = 1;
                    var selfTest = false;

                    for (var index = 0; index < args.Count; index++)
                    {{
                        var token = args[index];
                        switch (token)
                        {{
                            case "--self-test":
                                selfTest = true;
                                break;
                            case "--name":
                                name = ReadValue(args, ref index, "--name");
                                break;
                            case "--count":
                                var rawCount = ReadValue(args, ref index, "--count");
                                if (!int.TryParse(rawCount, out count) || count < 1 || count > 25)
                                {{
                                    throw new ArgumentException("--count must be an integer from 1 to 25.");
                                }}
                                break;
                            case "--help":
                            case "-h":
                                PrintUsage();
                                Environment.ExitCode = 0;
                                break;
                            default:
                                throw new ArgumentException($"Unknown argument: {{token}}");
                        }}
                    }}

                    return new AppOptions(name.Trim(), count, selfTest);
                }}

                public static IReadOnlyList<string> BuildOutput(AppOptions options)
                {{
                    if (string.IsNullOrWhiteSpace(options.Name))
                    {{
                        throw new ArgumentException("--name cannot be empty.");
                    }}

                    var lines = new List<string>();
                    for (var index = 1; index <= options.Count; index++)
                    {{
                        lines.Add($"{cs_title} ready for {{options.Name}} ({{index}}/{{options.Count}})");
                    }}
                    return lines;
                }}

                private static string ReadValue(IReadOnlyList<string> args, ref int index, string option)
                {{
                    if (index + 1 >= args.Count)
                    {{
                        throw new ArgumentException($"{{option}} requires a value.");
                    }}

                    index++;
                    return args[index];
                }}

                private static int RunSelfTest()
                {{
                    var parsed = Parse(new[] {{ "--name", "Validation", "--count", "2" }});
                    var output = BuildOutput(parsed);
                    if (parsed.Name != "Validation" || parsed.Count != 2 || output.Count != 2)
                    {{
                        Console.Error.WriteLine("Self-test failed: parser/output mismatch.");
                        return 1;
                    }}
                    if (!output[0].Contains("{cs_title}") || !output[0].Contains("Validation"))
                    {{
                        Console.Error.WriteLine("Self-test failed: output content mismatch.");
                        return 1;
                    }}

                    Console.WriteLine("Self-test passed.");
                    return 0;
                }}

                private static void PrintUsage()
                {{
                    Console.WriteLine("{cs_title}");
                    Console.WriteLine("Usage: {safe_name} [--name VALUE] [--count 1-25]");
                }}
            }}
            """
        ),
        "build.py": _strip(
            f"""
            from __future__ import annotations

            import shutil
            import subprocess
            import sys
            from pathlib import Path


            ROOT = Path(__file__).resolve().parent
            PROJECT = ROOT / "src" / "{safe_name}" / "{safe_name}.csproj"


            def run(command: list[str]) -> int:
                print("Running:", " ".join(command))
                return subprocess.call(command, cwd=str(ROOT))


            def main() -> int:
                if shutil.which("dotnet") is None:
                    print(".NET SDK was not found on PATH. Install .NET 8+ and rerun this script.", file=sys.stderr)
                    return 2

                if not PROJECT.exists():
                    print(f"Project file not found: {{PROJECT}}", file=sys.stderr)
                    return 2

                code = run(["dotnet", "restore", str(PROJECT)])
                if code != 0:
                    return code

                code = run(["dotnet", "build", str(PROJECT), "--configuration", "Release", "--no-restore"])
                if code != 0:
                    return code

                return run(
                    [
                        "dotnet",
                        "run",
                        "--project",
                        str(PROJECT),
                        "--configuration",
                        "Release",
                        "--no-build",
                        "--",
                        "--self-test",
                    ]
                )


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        ".gitignore": _strip(
            """
            bin
            obj
            .vs
            .vscode
            *.user
            *.suo
            *.nupkg
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            C# .NET console/exe project generated by Aegis Project Builder.

            ## Validate

            ```powershell
            python build.py
            ```

            ## Run

            ```powershell
            dotnet run --project src/{safe_name}/{safe_name}.csproj -- --name Aegis --count 3
            ```

            ## Publish A Windows Executable

            ```powershell
            dotnet publish src/{safe_name}/{safe_name}.csproj -c Release -r win-x64 --self-contained false
            ```
            """
        ),
    }


def dotnet_wpf_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    safe_name = "".join(part[:1].upper() + part[1:] for part in re.split(r"[-_]+", project_name) if part) or "AegisDesktop"
    cs_title = title.replace("\\", "\\\\").replace('"', '\\"')
    xaml_title = (
        title.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
    return {
        f"src/{safe_name}/{safe_name}.csproj": _strip(
            """
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>WinExe</OutputType>
                <TargetFramework>net8.0-windows</TargetFramework>
                <UseWPF>true</UseWPF>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
              </PropertyGroup>
            </Project>
            """
        ),
        f"src/{safe_name}/App.xaml": _strip(
            f"""
            <Application x:Class="{safe_name}.App"
                         xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                         xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                         StartupUri="MainWindow.xaml">
              <Application.Resources>
                <SolidColorBrush x:Key="AppBackground" Color="#071018" />
                <SolidColorBrush x:Key="PanelBackground" Color="#0C1620" />
                <SolidColorBrush x:Key="AccentBrush" Color="#27DE7D" />
                <SolidColorBrush x:Key="TextBrush" Color="#EDF7F3" />
                <SolidColorBrush x:Key="MutedBrush" Color="#9AA8B6" />
              </Application.Resources>
            </Application>
            """
        ),
        f"src/{safe_name}/App.xaml.cs": _strip(
            f"""
            using System.Windows;

            namespace {safe_name};

            public partial class App : Application
            {{
            }}
            """
        ),
        f"src/{safe_name}/DashboardState.cs": _strip(
            f"""
            namespace {safe_name};

            public sealed class DashboardState
            {{
                private readonly List<string> _activity = new();

                public DashboardState()
                {{
                    _activity.Add("Project initialized");
                    _activity.Add("Validation ready");
                }}

                public int BuildCount {{ get; private set; }}
                public IReadOnlyList<string> Activity => _activity;

                public void RecordBuild(string label)
                {{
                    if (string.IsNullOrWhiteSpace(label))
                    {{
                        throw new ArgumentException("label is required", nameof(label));
                    }}

                    BuildCount++;
                    _activity.Insert(0, $"{cs_title}: {{label.Trim()}} #{{BuildCount}}");
                }}

                public string Summary()
                {{
                    return BuildCount == 0
                        ? "{cs_title} is ready."
                        : $"{cs_title} has recorded {{BuildCount}} build event(s).";
                }}

                public bool SelfCheck()
                {{
                    RecordBuild("Smoke validation");
                    return BuildCount == 1 && Activity[0].Contains("Smoke validation", StringComparison.Ordinal);
                }}
            }}
            """
        ),
        f"src/{safe_name}/MainWindow.xaml": _strip(
            f"""
            <Window x:Class="{safe_name}.MainWindow"
                    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    Title="{xaml_title}"
                    Width="980"
                    Height="640"
                    MinWidth="760"
                    MinHeight="480"
                    Background="{{StaticResource AppBackground}}">
              <Grid Margin="28">
                <Grid.RowDefinitions>
                  <RowDefinition Height="Auto" />
                  <RowDefinition Height="*" />
                  <RowDefinition Height="Auto" />
                </Grid.RowDefinitions>

                <StackPanel>
                  <TextBlock Text="Desktop workspace"
                             Foreground="{{StaticResource AccentBrush}}"
                             FontSize="13"
                             FontWeight="SemiBold" />
                  <TextBlock Text="{xaml_title}"
                             Foreground="{{StaticResource TextBrush}}"
                             FontSize="34"
                             FontWeight="Bold"
                             Margin="0,8,0,4" />
                  <TextBlock Text="Native WPF shell with a testable state layer and package-free validation."
                             Foreground="{{StaticResource MutedBrush}}"
                             FontSize="15" />
                </StackPanel>

                <Border Grid.Row="1"
                        Margin="0,26,0,18"
                        Padding="20"
                        CornerRadius="8"
                        Background="{{StaticResource PanelBackground}}">
                  <Grid>
                    <Grid.ColumnDefinitions>
                      <ColumnDefinition Width="2*" />
                      <ColumnDefinition Width="*" />
                    </Grid.ColumnDefinitions>

                    <ListBox x:Name="ActivityList"
                             Background="#071018"
                             Foreground="{{StaticResource TextBrush}}"
                             BorderBrush="#203040" />

                    <StackPanel Grid.Column="1" Margin="20,0,0,0">
                      <TextBlock Text="Status"
                                 Foreground="{{StaticResource AccentBrush}}"
                                 FontSize="16"
                                 FontWeight="SemiBold" />
                      <TextBlock x:Name="SummaryText"
                                 Foreground="{{StaticResource TextBrush}}"
                                 TextWrapping="Wrap"
                                 Margin="0,10,0,18" />
                      <Button Content="Record Build Event"
                              Padding="12,8"
                              Click="RecordBuild_Click" />
                    </StackPanel>
                  </Grid>
                </Border>

                <TextBlock Grid.Row="2"
                           Foreground="{{StaticResource MutedBrush}}"
                           Text="Generated by Aegis Project Builder." />
              </Grid>
            </Window>
            """
        ),
        f"src/{safe_name}/MainWindow.xaml.cs": _strip(
            f"""
            using System.Windows;

            namespace {safe_name};

            public partial class MainWindow : Window
            {{
                private readonly DashboardState _state = new();

                public MainWindow()
                {{
                    InitializeComponent();
                    Refresh();
                }}

                private void RecordBuild_Click(object sender, RoutedEventArgs e)
                {{
                    _state.RecordBuild("Manual desktop action");
                    Refresh();
                }}

                private void Refresh()
                {{
                    SummaryText.Text = _state.Summary();
                    ActivityList.ItemsSource = null;
                    ActivityList.ItemsSource = _state.Activity;
                }}
            }}
            """
        ),
        f"tests/{safe_name}.Smoke/{safe_name}.Smoke.csproj": _strip(
            f"""
            <Project Sdk="Microsoft.NET.Sdk">
              <PropertyGroup>
                <OutputType>Exe</OutputType>
                <TargetFramework>net8.0-windows</TargetFramework>
                <Nullable>enable</Nullable>
                <ImplicitUsings>enable</ImplicitUsings>
              </PropertyGroup>
              <ItemGroup>
                <ProjectReference Include="../../src/{safe_name}/{safe_name}.csproj" />
              </ItemGroup>
            </Project>
            """
        ),
        f"tests/{safe_name}.Smoke/Program.cs": _strip(
            f"""
            using {safe_name};

            var state = new DashboardState();
            if (!state.SelfCheck())
            {{
                Console.Error.WriteLine("DashboardState self-check failed.");
                return 1;
            }}

            state.RecordBuild("Console smoke");
            if (state.BuildCount != 2 || !state.Summary().Contains("2 build event", StringComparison.Ordinal))
            {{
                Console.Error.WriteLine("DashboardState summary failed.");
                return 1;
            }}

            Console.WriteLine("WPF smoke passed.");
            return 0;
            """
        ),
        "build.py": _strip(
            f"""
            from __future__ import annotations

            import shutil
            import subprocess
            import sys
            from pathlib import Path


            ROOT = Path(__file__).resolve().parent
            APP_PROJECT = ROOT / "src" / "{safe_name}" / "{safe_name}.csproj"
            SMOKE_PROJECT = ROOT / "tests" / "{safe_name}.Smoke" / "{safe_name}.Smoke.csproj"


            def run(command: list[str]) -> int:
                print("Running:", " ".join(command))
                return subprocess.call(command, cwd=str(ROOT))


            def main() -> int:
                if shutil.which("dotnet") is None:
                    print(".NET SDK was not found on PATH. Install .NET 8+ and rerun this script.", file=sys.stderr)
                    return 2

                for project in (APP_PROJECT, SMOKE_PROJECT):
                    if not project.exists():
                        print(f"Project file not found: {{project}}", file=sys.stderr)
                        return 2

                code = run(["dotnet", "restore", str(APP_PROJECT)])
                if code != 0:
                    return code
                code = run(["dotnet", "restore", str(SMOKE_PROJECT)])
                if code != 0:
                    return code
                code = run(["dotnet", "build", str(APP_PROJECT), "--configuration", "Release", "--no-restore"])
                if code != 0:
                    return code
                code = run(["dotnet", "build", str(SMOKE_PROJECT), "--configuration", "Release", "--no-restore"])
                if code != 0:
                    return code
                return run(["dotnet", "run", "--project", str(SMOKE_PROJECT), "--configuration", "Release", "--no-build"])


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        ".gitignore": _strip(
            """
            bin
            obj
            .vs
            .vscode
            *.user
            *.suo
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            C# WPF desktop app generated by Aegis Project Builder.

            ## Validate

            ```powershell
            python build.py
            ```

            ## Run

            ```powershell
            dotnet run --project src/{safe_name}/{safe_name}.csproj
            ```

            The validation script builds the GUI project, builds a separate smoke console, and runs the smoke console without opening the WPF window.
            """
        ),
    }


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
