from __future__ import annotations

import re
import textwrap

from .project_scaffold_names import project_name as scaffold_project_name
from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def python_stdlib_api_template(project_name: str) -> dict[str, str]:
    package_name = _python_package_name(project_name)
    distribution_name = _manifest_package_name(project_name)
    title = _title_from_name(project_name)
    server_module = f"{package_name}.server"
    return {
        "pyproject.toml": _strip(
            f"""
            [project]
            name = "{distribution_name}"
            version = "0.1.0"
            description = "Dependency-free Python HTTP API scaffold generated by Aegis."
            requires-python = ">=3.11"
            dependencies = []

            [tool.aegis]
            validation = "python build.py"
            """
        ),
        f"src/{package_name}/__init__.py": _strip(
            """
            __version__ = "0.1.0"
            """
        ),
        f"src/{package_name}/store.py": _strip(
            """
            from __future__ import annotations

            import json
            import threading
            import uuid
            from datetime import datetime, timezone
            from pathlib import Path
            from typing import Any


            def utc_now() -> str:
                return datetime.now(timezone.utc).isoformat()


            class JsonItemStore:
                def __init__(self, path: Path | str, seed: list[dict[str, Any]] | None = None):
                    self.path = Path(path)
                    self.seed = seed if seed is not None else [
                        {"id": "seed-1", "name": "First item", "status": "active", "created_at": utc_now()}
                    ]
                    self._items: list[dict[str, Any]] = []
                    self._loaded = False
                    self._lock = threading.RLock()

                def list_items(self) -> list[dict[str, Any]]:
                    with self._lock:
                        self._load()
                        return [dict(item) for item in self._items]

                def get_item(self, item_id: str) -> dict[str, Any] | None:
                    with self._lock:
                        self._load()
                        for item in self._items:
                            if item["id"] == item_id:
                                return dict(item)
                        return None

                def create_item(self, payload: dict[str, Any]) -> dict[str, Any]:
                    name = str(payload.get("name", "")).strip()
                    if not name:
                        raise ValueError("name is required")

                    with self._lock:
                        self._load()
                        item = {
                            "id": uuid.uuid4().hex,
                            "name": name,
                            "status": str(payload.get("status", "active")),
                            "created_at": utc_now(),
                        }
                        self._items.insert(0, item)
                        self._save()
                        return dict(item)

                def update_item(self, item_id: str, payload: dict[str, Any]) -> dict[str, Any] | None:
                    with self._lock:
                        self._load()
                        for index, item in enumerate(self._items):
                            if item["id"] != item_id:
                                continue
                            updated = dict(item)
                            if "name" in payload:
                                name = str(payload["name"]).strip()
                                if not name:
                                    raise ValueError("name cannot be empty")
                                updated["name"] = name
                            if "status" in payload:
                                updated["status"] = str(payload["status"])
                            updated["updated_at"] = utc_now()
                            self._items[index] = updated
                            self._save()
                            return dict(updated)
                        return None

                def delete_item(self, item_id: str) -> bool:
                    with self._lock:
                        self._load()
                        before = len(self._items)
                        self._items = [item for item in self._items if item["id"] != item_id]
                        if len(self._items) == before:
                            return False
                        self._save()
                        return True

                def _load(self) -> None:
                    if self._loaded:
                        return
                    if self.path.exists():
                        payload = json.loads(self.path.read_text(encoding="utf-8"))
                        items = payload.get("items", [])
                        self._items = items if isinstance(items, list) else []
                    else:
                        self._items = [dict(item) for item in self.seed]
                        self._save()
                    self._loaded = True

                def _save(self) -> None:
                    self.path.parent.mkdir(parents=True, exist_ok=True)
                    self.path.write_text(json.dumps({"items": self._items}, indent=2) + "\\n", encoding="utf-8")
            """
        ),
        f"src/{package_name}/server.py": _strip(
            """
            from __future__ import annotations

            import json
            import os
            from http import HTTPStatus
            from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
            from pathlib import Path
            from urllib.parse import urlparse

            from .store import JsonItemStore


            def make_handler(store: JsonItemStore):
                class ApiHandler(BaseHTTPRequestHandler):
                    server_version = "__TITLE__/0.1"

                    def do_OPTIONS(self) -> None:
                        self._send_json(HTTPStatus.NO_CONTENT, {})

                    def do_GET(self) -> None:
                        path = urlparse(self.path).path
                        if path == "/health":
                            return self._send_json(HTTPStatus.OK, {"ok": True, "service": "__PACKAGE__", "version": "0.1.0"})
                        if path == "/api/items":
                            return self._send_json(HTTPStatus.OK, {"items": store.list_items()})
                        item_id = self._item_id(path)
                        if item_id:
                            item = store.get_item(item_id)
                            if item is None:
                                return self._send_json(HTTPStatus.NOT_FOUND, {"error": "item not found"})
                            return self._send_json(HTTPStatus.OK, {"item": item})
                        return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})

                    def do_POST(self) -> None:
                        path = urlparse(self.path).path
                        if path != "/api/items":
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})
                        try:
                            item = store.create_item(self._read_json())
                        except ValueError as error:
                            return self._send_json(HTTPStatus.BAD_REQUEST, {"error": str(error)})
                        return self._send_json(HTTPStatus.CREATED, {"item": item})

                    def do_PATCH(self) -> None:
                        item_id = self._item_id(urlparse(self.path).path)
                        if not item_id:
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})
                        try:
                            item = store.update_item(item_id, self._read_json())
                        except ValueError as error:
                            return self._send_json(HTTPStatus.BAD_REQUEST, {"error": str(error)})
                        if item is None:
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "item not found"})
                        return self._send_json(HTTPStatus.OK, {"item": item})

                    def do_DELETE(self) -> None:
                        item_id = self._item_id(urlparse(self.path).path)
                        if not item_id:
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})
                        if not store.delete_item(item_id):
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "item not found"})
                        return self._send_json(HTTPStatus.OK, {"ok": True})

                    def log_message(self, _format: str, *_args: object) -> None:
                        return

                    def _item_id(self, path: str) -> str:
                        prefix = "/api/items/"
                        return path[len(prefix):] if path.startswith(prefix) and len(path) > len(prefix) else ""

                    def _read_json(self) -> dict:
                        length = int(self.headers.get("content-length", "0") or "0")
                        if length > 1_000_000:
                            raise ValueError("request body is too large")
                        raw = self.rfile.read(length).decode("utf-8").strip() if length else "{}"
                        try:
                            payload = json.loads(raw or "{}")
                        except json.JSONDecodeError as error:
                            raise ValueError("request body must be valid JSON") from error
                        if not isinstance(payload, dict):
                            raise ValueError("request body must be a JSON object")
                        return payload

                    def _send_json(self, status: HTTPStatus, payload: dict) -> None:
                        body = b"" if status == HTTPStatus.NO_CONTENT else json.dumps(payload, indent=2).encode("utf-8")
                        self.send_response(status)
                        self.send_header("access-control-allow-origin", "*")
                        self.send_header("access-control-allow-methods", "GET, POST, PATCH, DELETE, OPTIONS")
                        self.send_header("access-control-allow-headers", "content-type")
                        self.send_header("content-type", "application/json; charset=utf-8")
                        self.send_header("content-length", str(len(body)))
                        self.end_headers()
                        if body:
                            self.wfile.write(body)

                return ApiHandler


            def create_server(
                host: str = "127.0.0.1",
                port: int = 8788,
                *,
                store: JsonItemStore | None = None,
                data_path: Path | str | None = None,
            ) -> ThreadingHTTPServer:
                resolved_store = store or JsonItemStore(Path(data_path or "data/items.json"))
                return ThreadingHTTPServer((host, port), make_handler(resolved_store))


            def main() -> int:
                host = os.environ.get("HOST", "127.0.0.1")
                port = int(os.environ.get("PORT", "8788"))
                server = create_server(host=host, port=port)
                print(f"__TITLE__ listening at http://{host}:{port}")
                try:
                    server.serve_forever()
                except KeyboardInterrupt:
                    pass
                finally:
                    server.server_close()
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ).replace("__PACKAGE__", package_name).replace("__TITLE__", title),
        "tests/test_api.py": _strip(
            """
            from __future__ import annotations

            import json
            import sys
            import tempfile
            import threading
            import unittest
            import urllib.error
            import urllib.request
            from pathlib import Path

            sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

            from __PACKAGE__.server import create_server
            from __PACKAGE__.store import JsonItemStore


            class ApiTests(unittest.TestCase):
                def setUp(self) -> None:
                    self.tempdir = tempfile.TemporaryDirectory()
                    data_path = Path(self.tempdir.name) / "items.json"
                    store = JsonItemStore(data_path, seed=[])
                    self.server = create_server(port=0, store=store)
                    self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
                    self.thread.start()
                    host, port = self.server.server_address
                    self.base_url = f"http://{host}:{port}"

                def tearDown(self) -> None:
                    self.server.shutdown()
                    self.server.server_close()
                    self.thread.join(timeout=5)
                    self.tempdir.cleanup()

                def test_health_endpoint(self) -> None:
                    status, payload = self.request("/health")
                    self.assertEqual(status, 200)
                    self.assertTrue(payload["ok"])

                def test_item_crud_flow(self) -> None:
                    status, payload = self.request("/api/items")
                    self.assertEqual(status, 200)
                    self.assertEqual(payload["items"], [])

                    status, payload = self.request("/api/items", method="POST", payload={"name": "Generated item", "status": "queued"})
                    self.assertEqual(status, 201)
                    item = payload["item"]
                    self.assertEqual(item["name"], "Generated item")

                    status, payload = self.request(f"/api/items/{item['id']}", method="PATCH", payload={"status": "complete"})
                    self.assertEqual(status, 200)
                    self.assertEqual(payload["item"]["status"], "complete")

                    status, payload = self.request(f"/api/items/{item['id']}", method="DELETE")
                    self.assertEqual(status, 200)
                    self.assertTrue(payload["ok"])

                def test_invalid_json_returns_client_error(self) -> None:
                    request = urllib.request.Request(
                        self.base_url + "/api/items",
                        data=b"{not json",
                        method="POST",
                        headers={"content-type": "application/json"},
                    )
                    with self.assertRaises(urllib.error.HTTPError) as raised:
                        urllib.request.urlopen(request, timeout=10)
                    error = raised.exception
                    try:
                        self.assertEqual(error.code, 400)
                    finally:
                        error.close()

                def request(self, path: str, *, method: str = "GET", payload: dict | None = None) -> tuple[int, dict]:
                    data = None if payload is None else json.dumps(payload).encode("utf-8")
                    request = urllib.request.Request(
                        self.base_url + path,
                        data=data,
                        method=method,
                        headers={"content-type": "application/json"},
                    )
                    with urllib.request.urlopen(request, timeout=10) as response:
                        return response.status, json.loads(response.read().decode("utf-8"))


            if __name__ == "__main__":
                unittest.main()
            """
        ).replace("__PACKAGE__", package_name),
        "build.py": _strip(
            """
            from __future__ import annotations

            import os
            import py_compile
            import subprocess
            import sys
            from pathlib import Path


            ROOT = Path(__file__).resolve().parent
            REQUIRED = [
                "pyproject.toml",
                "src/__PACKAGE__/__init__.py",
                "src/__PACKAGE__/store.py",
                "src/__PACKAGE__/server.py",
                "tests/test_api.py",
            ]


            def main() -> int:
                for relative in REQUIRED:
                    path = ROOT / relative
                    if not path.exists():
                        print(f"Missing required file: {relative}", file=sys.stderr)
                        return 1
                    if path.suffix == ".py":
                        py_compile.compile(str(path), doraise=True)

                env = os.environ.copy()
                src = str(ROOT / "src")
                env["PYTHONPATH"] = src + os.pathsep + env.get("PYTHONPATH", "")
                completed = subprocess.run(
                    [sys.executable, "-m", "unittest", "discover", "-s", "tests"],
                    cwd=ROOT,
                    env=env,
                )
                if completed.returncode != 0:
                    return completed.returncode
                print("Python stdlib HTTP API scaffold passed validation.")
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ).replace("__PACKAGE__", package_name),
        ".gitignore": _strip(
            """
            .venv
            __pycache__
            .pytest_cache
            data
            *.pyc
            *.log
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Dependency-free Python HTTP API scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            python build.py
            ```

            ## Run

            ```powershell
            $env:PYTHONPATH = "src"
            python -m {server_module}
            ```

            ## Endpoints

            - `GET /health`
            - `GET /api/items`
            - `POST /api/items`
            - `PATCH /api/items/:id`
            - `DELETE /api/items/:id`
            """
        ),
    }


def _python_package_name(project_name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", project_name.replace("-", "_")).strip("_").lower()
    if not cleaned:
        return "aegis_app"
    if cleaned[0].isdigit():
        cleaned = f"app_{cleaned}"
    return cleaned


def _manifest_package_name(project_name: str, fallback_prefix: str = "aegis") -> str:
    cleaned = scaffold_project_name(project_name)
    if cleaned[0].isdigit():
        cleaned = f"{fallback_prefix}-{cleaned}"
    return cleaned


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
