from __future__ import annotations

import json
import re
import textwrap

from .project_scaffold_names import project_name as scaffold_project_name
from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def node_cli_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = re.sub(r"[^a-z0-9-]+", "-", project_name.lower()).strip("-") or "aegis-node-cli"
    js_title = title.replace("\\", "\\\\").replace("'", "\\'")
    package_json = {
        "name": package_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "description": "A package-free Node.js CLI scaffold generated by Aegis.",
        "bin": {package_name: "./bin/cli.js"},
        "scripts": {
            "start": "node bin/cli.js",
            "test": "node --test tests/commands.test.js",
            "validate": "node build.js",
        },
        "engines": {"node": ">=20"},
    }
    return {
        "package.json": json.dumps(package_json, indent=2) + "\n",
        "bin/cli.js": _strip(
            """
            #!/usr/bin/env node

            import { runCli } from '../src/commands.js';

            const result = runCli(process.argv.slice(2));

            if (result.stdout) {
              console.log(result.stdout);
            }

            if (result.stderr) {
              console.error(result.stderr);
            }

            process.exitCode = result.exitCode;
            """
        ),
        "src/commands.js": _strip(
            """
            export const APP_TITLE = '__TITLE__';

            export function parseArgs(args) {
              const options = {
                name: 'Aegis',
                repeat: 1,
                uppercase: false,
                json: false
              };

              for (let index = 0; index < args.length; index += 1) {
                const token = args[index];
                if (token === '--name') {
                  options.name = readValue(args, index, token);
                  index += 1;
                } else if (token === '--repeat') {
                  const raw = readValue(args, index, token);
                  const repeat = Number.parseInt(raw, 10);
                  if (!Number.isInteger(repeat) || repeat < 1 || repeat > 25) {
                    throw new Error('--repeat must be an integer from 1 to 25.');
                  }
                  options.repeat = repeat;
                  index += 1;
                } else if (token === '--uppercase') {
                  options.uppercase = true;
                } else if (token === '--json') {
                  options.json = true;
                } else if (token === '--help' || token === '-h') {
                  options.help = true;
                } else {
                  throw new Error('Unknown argument: ' + token);
                }
              }

              if (!options.name.trim()) {
                throw new Error('--name cannot be empty.');
              }

              return options;
            }

            export function buildLines(options) {
              const lines = [];
              for (let index = 1; index <= options.repeat; index += 1) {
                const text = APP_TITLE + ' ready for ' + options.name + ' (' + index + '/' + options.repeat + ')';
                lines.push(options.uppercase ? text.toUpperCase() : text);
              }
              return lines;
            }

            export function runCli(args) {
              try {
                const options = parseArgs(args);
                if (options.help) {
                  return {
                    exitCode: 0,
                    stdout: usage(),
                    stderr: ''
                  };
                }

                const lines = buildLines(options);
                return {
                  exitCode: 0,
                  stdout: options.json
                    ? JSON.stringify({ app: APP_TITLE, lines }, null, 2)
                    : lines.join('\\n'),
                  stderr: ''
                };
              } catch (error) {
                return {
                  exitCode: 2,
                  stdout: '',
                  stderr: error.message + '\\n\\n' + usage()
                };
              }
            }

            function readValue(args, index, option) {
              if (index + 1 >= args.length) {
                throw new Error(option + ' requires a value.');
              }
              return args[index + 1];
            }

            function usage() {
              return [
                APP_TITLE,
                '',
                'Usage:',
                '  node bin/cli.js [--name VALUE] [--repeat 1-25] [--uppercase] [--json]',
                '',
                'Examples:',
                '  node bin/cli.js --name Aegis --repeat 2',
                '  node bin/cli.js --json'
              ].join('\\n');
            }
            """
        ).replace("__TITLE__", js_title),
        "tests/commands.test.js": _strip(
            """
            import test from 'node:test';
            import assert from 'node:assert/strict';

            import { buildLines, parseArgs, runCli } from '../src/commands.js';

            test('parseArgs reads name, repeat, and flags', () => {
              const options = parseArgs(['--name', 'Mercy', '--repeat', '2', '--uppercase']);
              assert.equal(options.name, 'Mercy');
              assert.equal(options.repeat, 2);
              assert.equal(options.uppercase, true);
            });

            test('buildLines creates repeatable output', () => {
              const lines = buildLines({ name: 'Aegis', repeat: 2, uppercase: false });
              assert.equal(lines.length, 2);
              assert.match(lines[0], /Aegis/);
            });

            test('runCli returns an error for invalid repeat values', () => {
              const result = runCli(['--repeat', '0']);
              assert.equal(result.exitCode, 2);
              assert.match(result.stderr, /--repeat/);
            });
            """
        ),
        "build.js": _strip(
            """
            import { spawnSync } from 'node:child_process';
            import { existsSync } from 'node:fs';

            const requiredFiles = [
              'package.json',
              'bin/cli.js',
              'src/commands.js',
              'tests/commands.test.js'
            ];

            for (const file of requiredFiles) {
              if (!existsSync(file)) {
                console.error('Missing required file:', file);
                process.exit(1);
              }
            }

            const commands = [
              ['node', ['--check', 'bin/cli.js']],
              ['node', ['--check', 'src/commands.js']],
              ['node', ['--test', 'tests/commands.test.js']],
              ['node', ['bin/cli.js', '--name', 'Validation', '--repeat', '2']]
            ];

            for (const [command, args] of commands) {
              console.log('Running:', command, ...args);
              const completed = spawnSync(command, args, {
                stdio: 'inherit'
              });
              if (completed.status !== 0) {
                process.exit(completed.status ?? 1);
              }
            }

            console.log('Node.js CLI scaffold passed validation.');
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            coverage
            dist
            *.log
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Node.js CLI scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            node build.js
            ```

            ## Run

            ```powershell
            node bin/cli.js --name Aegis --repeat 2
            node bin/cli.js --json
            ```

            The package also exposes a bin entry in `package.json` for later packaging or `npm link` workflows.
            """
        ),
    }


def node_http_api_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = re.sub(r"[^a-z0-9-]+", "-", project_name.lower()).strip("-") or "aegis-node-api"
    package_json = {
        "name": package_name,
        "version": "0.1.0",
        "private": True,
        "type": "module",
        "description": "Dependency-free Node.js HTTP API scaffold generated by Aegis.",
        "scripts": {
            "start": "node src/server.js",
            "test": "node --test tests/api.test.js",
            "validate": "node build.js",
        },
        "engines": {"node": ">=20"},
    }
    return {
        "package.json": json.dumps(package_json, indent=2) + "\n",
        "src/store.js": _strip(
            """
            export function createItemStore(initialItems = []) {
              let nextId = 1;
              const items = new Map();

              for (const item of initialItems) {
                const id = String(item.id ?? nextId++);
                items.set(id, {
                  id,
                  name: String(item.name ?? 'Untitled item'),
                  status: String(item.status ?? 'active'),
                  createdAt: item.createdAt ?? new Date().toISOString()
                });
              }

              return {
                list() {
                  return [...items.values()];
                },
                find(id) {
                  return items.get(String(id)) ?? null;
                },
                create(payload) {
                  const name = String(payload?.name ?? '').trim();
                  if (!name) {
                    throw new Error('name is required');
                  }
                  const id = String(nextId++);
                  const item = {
                    id,
                    name,
                    status: String(payload?.status ?? 'active'),
                    createdAt: new Date().toISOString()
                  };
                  items.set(id, item);
                  return item;
                }
              };
            }
            """
        ),
        "src/server.js": _strip(
            """
            import { createServer } from 'node:http';
            import { pathToFileURL } from 'node:url';

            import { createItemStore } from './store.js';

            const defaultStore = createItemStore([
              { id: 'seed-1', name: 'First API item', status: 'active' }
            ]);

            export function createApiServer({ store = defaultStore } = {}) {
              return createServer(async (request, response) => {
                const url = new URL(request.url ?? '/', 'http://localhost');
                const method = request.method ?? 'GET';

                try {
                  if (method === 'GET' && url.pathname === '/health') {
                    return sendJson(response, 200, {
                      ok: true,
                      service: 'aegis-node-api',
                      timestamp: new Date().toISOString()
                    });
                  }

                  if (method === 'GET' && url.pathname === '/api/items') {
                    return sendJson(response, 200, { items: store.list() });
                  }

                  if (method === 'POST' && url.pathname === '/api/items') {
                    const payload = await readJson(request);
                    const item = store.create(payload);
                    return sendJson(response, 201, { item });
                  }

                  const itemMatch = url.pathname.match(/^\\/api\\/items\\/([^/]+)$/);
                  if (method === 'GET' && itemMatch) {
                    const item = store.find(itemMatch[1]);
                    if (!item) {
                      return sendJson(response, 404, { error: 'item not found' });
                    }
                    return sendJson(response, 200, { item });
                  }

                  return sendJson(response, 404, { error: 'route not found' });
                } catch (error) {
                  return sendJson(response, 400, { error: error.message });
                }
              });
            }

            async function readJson(request) {
              const chunks = [];
              let size = 0;

              for await (const chunk of request) {
                size += chunk.length;
                if (size > 1_000_000) {
                  throw new Error('request body is too large');
                }
                chunks.push(chunk);
              }

              const body = Buffer.concat(chunks).toString('utf8').trim();
              if (!body) {
                return {};
              }

              try {
                return JSON.parse(body);
              } catch {
                throw new Error('request body must be valid JSON');
              }
            }

            function sendJson(response, statusCode, payload) {
              const body = JSON.stringify(payload, null, 2);
              response.writeHead(statusCode, {
                'access-control-allow-origin': '*',
                'content-type': 'application/json; charset=utf-8'
              });
              response.end(body);
            }

            if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
              const port = Number.parseInt(process.env.PORT || '8788', 10);
              createApiServer().listen(port, '127.0.0.1', () => {
                console.log(`API listening at http://127.0.0.1:${port}`);
              });
            }
            """
        ),
        "tests/api.test.js": _strip(
            """
            import test from 'node:test';
            import assert from 'node:assert/strict';

            import { createApiServer } from '../src/server.js';
            import { createItemStore } from '../src/store.js';

            test('health endpoint returns service status', async () => {
              const fixture = await startServer();
              try {
                const response = await fetch(`${fixture.baseUrl}/health`);
                const payload = await response.json();
                assert.equal(response.status, 200);
                assert.equal(payload.ok, true);
              } finally {
                await fixture.close();
              }
            });

            test('item routes list, create, and fetch records', async () => {
              const fixture = await startServer();
              try {
                const listResponse = await fetch(`${fixture.baseUrl}/api/items`);
                const listPayload = await listResponse.json();
                assert.equal(listResponse.status, 200);
                assert.equal(listPayload.items.length, 1);

                const createResponse = await fetch(`${fixture.baseUrl}/api/items`, {
                  method: 'POST',
                  headers: { 'content-type': 'application/json' },
                  body: JSON.stringify({ name: 'Generated item', status: 'queued' })
                });
                const createPayload = await createResponse.json();
                assert.equal(createResponse.status, 201);
                assert.equal(createPayload.item.name, 'Generated item');

                const getResponse = await fetch(`${fixture.baseUrl}/api/items/${createPayload.item.id}`);
                const getPayload = await getResponse.json();
                assert.equal(getResponse.status, 200);
                assert.equal(getPayload.item.status, 'queued');
              } finally {
                await fixture.close();
              }
            });

            test('invalid JSON returns a client error', async () => {
              const fixture = await startServer();
              try {
                const response = await fetch(`${fixture.baseUrl}/api/items`, {
                  method: 'POST',
                  headers: { 'content-type': 'application/json' },
                  body: '{not json'
                });
                const payload = await response.json();
                assert.equal(response.status, 400);
                assert.match(payload.error, /valid JSON/);
              } finally {
                await fixture.close();
              }
            });

            async function startServer() {
              const store = createItemStore([{ id: 'seed', name: 'Seed item', status: 'active' }]);
              const server = createApiServer({ store });
              await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
              const address = server.address();
              return {
                baseUrl: `http://${address.address}:${address.port}`,
                close: () => new Promise((resolve, reject) => {
                  server.close((error) => (error ? reject(error) : resolve()));
                })
              };
            }
            """
        ),
        "build.js": _strip(
            """
            import { spawnSync } from 'node:child_process';
            import { existsSync, readFileSync } from 'node:fs';

            const requiredFiles = [
              'package.json',
              'src/server.js',
              'src/store.js',
              'tests/api.test.js'
            ];

            for (const file of requiredFiles) {
              if (!existsSync(file)) {
                console.error('Missing required file:', file);
                process.exit(1);
              }
            }

            const server = readFileSync('src/server.js', 'utf8');
            for (const marker of ['/health', '/api/items', 'createApiServer', 'readJson']) {
              if (!server.includes(marker)) {
                console.error('src/server.js is missing:', marker);
                process.exit(1);
              }
            }

            const commands = [
              ['node', ['--check', 'src/server.js']],
              ['node', ['--check', 'src/store.js']],
              ['node', ['--test', 'tests/api.test.js']]
            ];

            for (const [command, args] of commands) {
              console.log('Running:', command, ...args);
              const completed = spawnSync(command, args, { stdio: 'inherit' });
              if (completed.status !== 0) {
                process.exit(completed.status ?? 1);
              }
            }

            console.log('Node.js HTTP API scaffold passed validation.');
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            coverage
            dist
            *.log
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Dependency-free Node.js HTTP API scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            node build.js
            ```

            ## Run

            ```powershell
            node src/server.js
            ```

            ## Endpoints

            - `GET /health`
            - `GET /api/items`
            - `POST /api/items`
            - `GET /api/items/:id`
            """
        ),
    }



def express_ts_template(project_name: str) -> dict[str, str]:
    title = _title_from_name(project_name)
    package_name = _manifest_package_name(project_name)
    return {
        "package.json": _strip(
            f"""
            {{
              "name": "{package_name}",
              "version": "0.1.0",
              "private": true,
              "type": "module",
              "scripts": {{
                "dev": "tsx watch src/server.ts",
                "build": "tsc -p tsconfig.json",
                "start": "node dist/server.js",
                "typecheck": "tsc -p tsconfig.json --noEmit"
              }},
              "dependencies": {{
                "dotenv": "^16.4.7",
                "express": "^4.21.2"
              }},
              "devDependencies": {{
                "@types/express": "^5.0.0",
                "@types/node": "^22.10.1",
                "tsx": "^4.19.2",
                "typescript": "^5.7.2"
              }}
            }}
            """
        ),
        "tsconfig.json": _strip(
            """
            {
              "compilerOptions": {
                "target": "ES2022",
                "module": "NodeNext",
                "moduleResolution": "NodeNext",
                "strict": true,
                "esModuleInterop": true,
                "skipLibCheck": true,
                "forceConsistentCasingInFileNames": true,
                "outDir": "dist",
                "rootDir": "src"
              },
              "include": ["src/**/*.ts"]
            }
            """
        ),
        "src/config.ts": _strip(
            f"""
            import "dotenv/config";

            export const config = {{
              appName: process.env.APP_NAME ?? "{title}",
              nodeEnv: process.env.NODE_ENV ?? "development",
              port: Number(process.env.PORT ?? 3000)
            }};
            """
        ),
        "src/routes/health.ts": _strip(
            """
            import { Router } from "express";

            import { config } from "../config.js";

            export const healthRouter = Router();

            healthRouter.get("/health", (_request, response) => {
              response.json({
                status: "ok",
                service: config.appName,
                environment: config.nodeEnv
              });
            });
            """
        ),
        "src/server.ts": _strip(
            """
            import express from "express";

            import { config } from "./config.js";
            import { healthRouter } from "./routes/health.js";

            export function createApp() {
              const app = express();

              app.use(express.json({ limit: "1mb" }));
              app.use(healthRouter);
              app.get("/api/status", (_request, response) => {
                response.json({ status: "ready" });
              });

              return app;
            }

            if (process.env.NODE_ENV !== "test") {
              createApp().listen(config.port, () => {
                console.log(`${config.appName} listening on http://127.0.0.1:${config.port}`);
              });
            }
            """
        ),
        ".env.example": _strip(
            f"""
            APP_NAME="{title}"
            NODE_ENV=development
            PORT=3000
            """
        ),
        ".gitignore": _strip(
            """
            node_modules
            dist
            .env
            npm-debug.log*
            pnpm-debug.log*
            yarn-debug.log*
            yarn-error.log*
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Express TypeScript API generated by Aegis Project Builder.

            ```bash
            npm install
            npm run dev
            ```

            Validate with:

            ```bash
            npm run build
            ```
            """
        ),
    }


def _manifest_package_name(project_name: str, fallback_prefix: str = "aegis") -> str:
    cleaned = scaffold_project_name(project_name)
    if cleaned[0].isdigit():
        cleaned = f"{fallback_prefix}-{cleaned}"
    return cleaned


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
