from __future__ import annotations

import re
import textwrap

from .project_scaffold_names import project_name as scaffold_project_name
from .project_scaffold_targets import title_from_name as scaffold_title_from_name


def python_stdlib_api_template(project_name: str) -> dict[str, str]:
    package_name = _python_package_name(project_name)
    distribution_name = _manifest_package_name(project_name)
    title = _title_from_name(project_name)
    server_module = f"{package_name}.server"
    return {
        "pyproject.toml": _strip(
            f"""
            [project]
            name = "{distribution_name}"
            version = "0.1.0"
            description = "Dependency-free Python HTTP API scaffold generated by Aegis."
            requires-python = ">=3.11"
            dependencies = []

            [tool.aegis]
            validation = "python build.py"
            """
        ),
        f"src/{package_name}/__init__.py": _strip(
            """
            __version__ = "0.1.0"
            """
        ),
        f"src/{package_name}/store.py": _strip(
            """
            from __future__ import annotations

            import json
            import threading
            import uuid
            from datetime import datetime, timezone
            from pathlib import Path
            from typing import Any


            def utc_now() -> str:
                return datetime.now(timezone.utc).isoformat()


            class JsonItemStore:
                def __init__(self, path: Path | str, seed: list[dict[str, Any]] | None = None):
                    self.path = Path(path)
                    self.seed = seed if seed is not None else [
                        {"id": "seed-1", "name": "First item", "status": "active", "created_at": utc_now()}
                    ]
                    self._items: list[dict[str, Any]] = []
                    self._loaded = False
                    self._lock = threading.RLock()

                def list_items(self) -> list[dict[str, Any]]:
                    with self._lock:
                        self._load()
                        return [dict(item) for item in self._items]

                def get_item(self, item_id: str) -> dict[str, Any] | None:
                    with self._lock:
                        self._load()
                        for item in self._items:
                            if item["id"] == item_id:
                                return dict(item)
                        return None

                def create_item(self, payload: dict[str, Any]) -> dict[str, Any]:
                    name = str(payload.get("name", "")).strip()
                    if not name:
                        raise ValueError("name is required")

                    with self._lock:
                        self._load()
                        item = {
                            "id": uuid.uuid4().hex,
                            "name": name,
                            "status": str(payload.get("status", "active")),
                            "created_at": utc_now(),
                        }
                        self._items.insert(0, item)
                        self._save()
                        return dict(item)

                def update_item(self, item_id: str, payload: dict[str, Any]) -> dict[str, Any] | None:
                    with self._lock:
                        self._load()
                        for index, item in enumerate(self._items):
                            if item["id"] != item_id:
                                continue
                            updated = dict(item)
                            if "name" in payload:
                                name = str(payload["name"]).strip()
                                if not name:
                                    raise ValueError("name cannot be empty")
                                updated["name"] = name
                            if "status" in payload:
                                updated["status"] = str(payload["status"])
                            updated["updated_at"] = utc_now()
                            self._items[index] = updated
                            self._save()
                            return dict(updated)
                        return None

                def delete_item(self, item_id: str) -> bool:
                    with self._lock:
                        self._load()
                        before = len(self._items)
                        self._items = [item for item in self._items if item["id"] != item_id]
                        if len(self._items) == before:
                            return False
                        self._save()
                        return True

                def _load(self) -> None:
                    if self._loaded:
                        return
                    if self.path.exists():
                        payload = json.loads(self.path.read_text(encoding="utf-8"))
                        items = payload.get("items", [])
                        self._items = items if isinstance(items, list) else []
                    else:
                        self._items = [dict(item) for item in self.seed]
                        self._save()
                    self._loaded = True

                def _save(self) -> None:
                    self.path.parent.mkdir(parents=True, exist_ok=True)
                    self.path.write_text(json.dumps({"items": self._items}, indent=2) + "\\n", encoding="utf-8")
            """
        ),
        f"src/{package_name}/server.py": _strip(
            """
            from __future__ import annotations

            import json
            import os
            from http import HTTPStatus
            from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
            from pathlib import Path
            from urllib.parse import urlparse

            from .store import JsonItemStore


            def make_handler(store: JsonItemStore):
                class ApiHandler(BaseHTTPRequestHandler):
                    server_version = "__TITLE__/0.1"

                    def do_OPTIONS(self) -> None:
                        self._send_json(HTTPStatus.NO_CONTENT, {})

                    def do_GET(self) -> None:
                        path = urlparse(self.path).path
                        if path == "/health":
                            return self._send_json(HTTPStatus.OK, {"ok": True, "service": "__PACKAGE__", "version": "0.1.0"})
                        if path == "/api/items":
                            return self._send_json(HTTPStatus.OK, {"items": store.list_items()})
                        item_id = self._item_id(path)
                        if item_id:
                            item = store.get_item(item_id)
                            if item is None:
                                return self._send_json(HTTPStatus.NOT_FOUND, {"error": "item not found"})
                            return self._send_json(HTTPStatus.OK, {"item": item})
                        return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})

                    def do_POST(self) -> None:
                        path = urlparse(self.path).path
                        if path != "/api/items":
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})
                        try:
                            item = store.create_item(self._read_json())
                        except ValueError as error:
                            return self._send_json(HTTPStatus.BAD_REQUEST, {"error": str(error)})
                        return self._send_json(HTTPStatus.CREATED, {"item": item})

                    def do_PATCH(self) -> None:
                        item_id = self._item_id(urlparse(self.path).path)
                        if not item_id:
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})
                        try:
                            item = store.update_item(item_id, self._read_json())
                        except ValueError as error:
                            return self._send_json(HTTPStatus.BAD_REQUEST, {"error": str(error)})
                        if item is None:
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "item not found"})
                        return self._send_json(HTTPStatus.OK, {"item": item})

                    def do_DELETE(self) -> None:
                        item_id = self._item_id(urlparse(self.path).path)
                        if not item_id:
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "route not found"})
                        if not store.delete_item(item_id):
                            return self._send_json(HTTPStatus.NOT_FOUND, {"error": "item not found"})
                        return self._send_json(HTTPStatus.OK, {"ok": True})

                    def log_message(self, _format: str, *_args: object) -> None:
                        return

                    def _item_id(self, path: str) -> str:
                        prefix = "/api/items/"
                        return path[len(prefix):] if path.startswith(prefix) and len(path) > len(prefix) else ""

                    def _read_json(self) -> dict:
                        length = int(self.headers.get("content-length", "0") or "0")
                        if length > 1_000_000:
                            raise ValueError("request body is too large")
                        raw = self.rfile.read(length).decode("utf-8").strip() if length else "{}"
                        try:
                            payload = json.loads(raw or "{}")
                        except json.JSONDecodeError as error:
                            raise ValueError("request body must be valid JSON") from error
                        if not isinstance(payload, dict):
                            raise ValueError("request body must be a JSON object")
                        return payload

                    def _send_json(self, status: HTTPStatus, payload: dict) -> None:
                        body = b"" if status == HTTPStatus.NO_CONTENT else json.dumps(payload, indent=2).encode("utf-8")
                        self.send_response(status)
                        self.send_header("access-control-allow-origin", "*")
                        self.send_header("access-control-allow-methods", "GET, POST, PATCH, DELETE, OPTIONS")
                        self.send_header("access-control-allow-headers", "content-type")
                        self.send_header("content-type", "application/json; charset=utf-8")
                        self.send_header("content-length", str(len(body)))
                        self.end_headers()
                        if body:
                            self.wfile.write(body)

                return ApiHandler


            def create_server(
                host: str = "127.0.0.1",
                port: int = 8788,
                *,
                store: JsonItemStore | None = None,
                data_path: Path | str | None = None,
            ) -> ThreadingHTTPServer:
                resolved_store = store or JsonItemStore(Path(data_path or "data/items.json"))
                return ThreadingHTTPServer((host, port), make_handler(resolved_store))


            def main() -> int:
                host = os.environ.get("HOST", "127.0.0.1")
                port = int(os.environ.get("PORT", "8788"))
                server = create_server(host=host, port=port)
                print(f"__TITLE__ listening at http://{host}:{port}")
                try:
                    server.serve_forever()
                except KeyboardInterrupt:
                    pass
                finally:
                    server.server_close()
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ).replace("__PACKAGE__", package_name).replace("__TITLE__", title),
        "tests/test_api.py": _strip(
            """
            from __future__ import annotations

            import json
            import sys
            import tempfile
            import threading
            import unittest
            import urllib.error
            import urllib.request
            from pathlib import Path

            sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

            from __PACKAGE__.server import create_server
            from __PACKAGE__.store import JsonItemStore


            class ApiTests(unittest.TestCase):
                def setUp(self) -> None:
                    self.tempdir = tempfile.TemporaryDirectory()
                    data_path = Path(self.tempdir.name) / "items.json"
                    store = JsonItemStore(data_path, seed=[])
                    self.server = create_server(port=0, store=store)
                    self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)
                    self.thread.start()
                    host, port = self.server.server_address
                    self.base_url = f"http://{host}:{port}"

                def tearDown(self) -> None:
                    self.server.shutdown()
                    self.server.server_close()
                    self.thread.join(timeout=5)
                    self.tempdir.cleanup()

                def test_health_endpoint(self) -> None:
                    status, payload = self.request("/health")
                    self.assertEqual(status, 200)
                    self.assertTrue(payload["ok"])

                def test_item_crud_flow(self) -> None:
                    status, payload = self.request("/api/items")
                    self.assertEqual(status, 200)
                    self.assertEqual(payload["items"], [])

                    status, payload = self.request("/api/items", method="POST", payload={"name": "Generated item", "status": "queued"})
                    self.assertEqual(status, 201)
                    item = payload["item"]
                    self.assertEqual(item["name"], "Generated item")

                    status, payload = self.request(f"/api/items/{item['id']}", method="PATCH", payload={"status": "complete"})
                    self.assertEqual(status, 200)
                    self.assertEqual(payload["item"]["status"], "complete")

                    status, payload = self.request(f"/api/items/{item['id']}", method="DELETE")
                    self.assertEqual(status, 200)
                    self.assertTrue(payload["ok"])

                def test_invalid_json_returns_client_error(self) -> None:
                    request = urllib.request.Request(
                        self.base_url + "/api/items",
                        data=b"{not json",
                        method="POST",
                        headers={"content-type": "application/json"},
                    )
                    with self.assertRaises(urllib.error.HTTPError) as raised:
                        urllib.request.urlopen(request, timeout=10)
                    error = raised.exception
                    try:
                        self.assertEqual(error.code, 400)
                    finally:
                        error.close()

                def request(self, path: str, *, method: str = "GET", payload: dict | None = None) -> tuple[int, dict]:
                    data = None if payload is None else json.dumps(payload).encode("utf-8")
                    request = urllib.request.Request(
                        self.base_url + path,
                        data=data,
                        method=method,
                        headers={"content-type": "application/json"},
                    )
                    with urllib.request.urlopen(request, timeout=10) as response:
                        return response.status, json.loads(response.read().decode("utf-8"))


            if __name__ == "__main__":
                unittest.main()
            """
        ).replace("__PACKAGE__", package_name),
        "build.py": _strip(
            """
            from __future__ import annotations

            import os
            import py_compile
            import subprocess
            import sys
            from pathlib import Path


            ROOT = Path(__file__).resolve().parent
            REQUIRED = [
                "pyproject.toml",
                "src/__PACKAGE__/__init__.py",
                "src/__PACKAGE__/store.py",
                "src/__PACKAGE__/server.py",
                "tests/test_api.py",
            ]


            def main() -> int:
                for relative in REQUIRED:
                    path = ROOT / relative
                    if not path.exists():
                        print(f"Missing required file: {relative}", file=sys.stderr)
                        return 1
                    if path.suffix == ".py":
                        py_compile.compile(str(path), doraise=True)

                env = os.environ.copy()
                src = str(ROOT / "src")
                env["PYTHONPATH"] = src + os.pathsep + env.get("PYTHONPATH", "")
                completed = subprocess.run(
                    [sys.executable, "-m", "unittest", "discover", "-s", "tests"],
                    cwd=ROOT,
                    env=env,
                )
                if completed.returncode != 0:
                    return completed.returncode
                print("Python stdlib HTTP API scaffold passed validation.")
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ).replace("__PACKAGE__", package_name),
        ".gitignore": _strip(
            """
            .venv
            __pycache__
            .pytest_cache
            data
            *.pyc
            *.log
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Dependency-free Python HTTP API scaffold generated by Aegis Project Builder.

            ## Validate

            ```powershell
            python build.py
            ```

            ## Run

            ```powershell
            $env:PYTHONPATH = "src"
            python -m {server_module}
            ```

            ## Endpoints

            - `GET /health`
            - `GET /api/items`
            - `POST /api/items`
            - `PATCH /api/items/:id`
            - `DELETE /api/items/:id`
            """
        ),
    }


def sqlite_python_db_template(project_name: str) -> dict[str, str]:
    package_name = _python_package_name(project_name)
    title = _title_from_name(project_name)
    return {
        "schema.sql": _strip(
            """
            PRAGMA foreign_keys = ON;

            CREATE TABLE IF NOT EXISTS app_metadata (
              key TEXT PRIMARY KEY,
              value TEXT NOT NULL,
              updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE TABLE IF NOT EXISTS inventory_items (
              id INTEGER PRIMARY KEY AUTOINCREMENT,
              name TEXT NOT NULL UNIQUE,
              category TEXT NOT NULL DEFAULT 'general',
              quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
              status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived')),
              notes TEXT NOT NULL DEFAULT '',
              created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
              updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
            );

            CREATE INDEX IF NOT EXISTS idx_inventory_items_category
              ON inventory_items(category);

            CREATE INDEX IF NOT EXISTS idx_inventory_items_status
              ON inventory_items(status);

            CREATE TRIGGER IF NOT EXISTS trg_inventory_items_updated_at
            AFTER UPDATE ON inventory_items
            FOR EACH ROW
            BEGIN
              UPDATE inventory_items SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
            END;

            CREATE VIEW IF NOT EXISTS inventory_summary AS
            SELECT
              category,
              COUNT(*) AS item_count,
              COALESCE(SUM(quantity), 0) AS total_quantity
            FROM inventory_items
            WHERE status = 'active'
            GROUP BY category;
            """
        ),
        "seed.sql": _strip(
            f"""
            INSERT OR REPLACE INTO app_metadata(key, value)
            VALUES ('project_name', '{title}');

            INSERT OR IGNORE INTO inventory_items(name, category, quantity, notes)
            VALUES
              ('Starter Record', 'general', 3, 'Generated seed row used by smoke tests.'),
              ('Backlog Item', 'planning', 7, 'Represents work waiting for a feature pass.'),
              ('Validated Item', 'quality', 1, 'Confirms the schema, seed, and reporting path are active.');
            """
        ),
        "queries/report.sql": _strip(
            """
            SELECT
              category,
              item_count,
              total_quantity
            FROM inventory_summary
            ORDER BY category;
            """
        ),
        f"src/{package_name}/__init__.py": _strip(
            """
            from .database import DEFAULT_DB, add_item, initialize_database, list_items, summary

            __all__ = [
                "DEFAULT_DB",
                "add_item",
                "initialize_database",
                "list_items",
                "summary",
            ]
            """
        ),
        f"src/{package_name}/database.py": _strip(
            """
            from __future__ import annotations

            import sqlite3
            from contextlib import closing
            from pathlib import Path
            from typing import Any


            ROOT = Path(__file__).resolve().parents[2]
            SCHEMA_PATH = ROOT / "schema.sql"
            SEED_PATH = ROOT / "seed.sql"
            DEFAULT_DB = ROOT / "data" / "app.sqlite3"


            def connect(db_path: Path | str = DEFAULT_DB) -> sqlite3.Connection:
                path = Path(db_path)
                path.parent.mkdir(parents=True, exist_ok=True)
                connection = sqlite3.connect(path)
                connection.row_factory = sqlite3.Row
                connection.execute("PRAGMA foreign_keys = ON")
                return connection


            def run_script(connection: sqlite3.Connection, script_path: Path) -> None:
                connection.executescript(script_path.read_text(encoding="utf-8"))


            def initialize_database(
                db_path: Path | str = DEFAULT_DB,
                *,
                seed: bool = True,
                reset: bool = False,
            ) -> Path:
                path = Path(db_path)
                if reset and path.exists():
                    path.unlink()
                path.parent.mkdir(parents=True, exist_ok=True)
                with closing(connect(path)) as connection:
                    run_script(connection, SCHEMA_PATH)
                    if seed:
                        run_script(connection, SEED_PATH)
                    connection.commit()
                return path


            def add_item(
                db_path: Path | str,
                name: str,
                *,
                category: str = "general",
                quantity: int = 0,
                notes: str = "",
            ) -> int:
                if not name.strip():
                    raise ValueError("name is required")
                if quantity < 0:
                    raise ValueError("quantity must be greater than or equal to zero")
                with closing(connect(db_path)) as connection:
                    cursor = connection.execute(
                        "INSERT INTO inventory_items(name, category, quantity, notes) VALUES (?, ?, ?, ?)",
                        (name.strip(), category.strip() or "general", quantity, notes.strip()),
                    )
                    connection.commit()
                    return int(cursor.lastrowid)


            def list_items(db_path: Path | str = DEFAULT_DB) -> list[dict[str, Any]]:
                with closing(connect(db_path)) as connection:
                    rows = connection.execute(
                        '''
                        SELECT id, name, category, quantity, status, notes, created_at, updated_at
                        FROM inventory_items
                        ORDER BY category, name
                        '''
                    ).fetchall()
                return [dict(row) for row in rows]


            def summary(db_path: Path | str = DEFAULT_DB) -> dict[str, Any]:
                with closing(connect(db_path)) as connection:
                    total = connection.execute(
                        '''
                        SELECT
                          COUNT(*) AS item_count,
                          COALESCE(SUM(quantity), 0) AS total_quantity
                        FROM inventory_items
                        WHERE status = 'active'
                        '''
                    ).fetchone()
                    categories = connection.execute(
                        '''
                        SELECT category, item_count, total_quantity
                        FROM inventory_summary
                        ORDER BY category
                        '''
                    ).fetchall()
                return {
                    "item_count": int(total["item_count"] or 0),
                    "total_quantity": int(total["total_quantity"] or 0),
                    "categories": [dict(row) for row in categories],
                }
            """
        ),
        f"src/{package_name}/cli.py": _strip(
            f"""
            from __future__ import annotations

            import argparse
            import json
            from pathlib import Path

            from .database import DEFAULT_DB, add_item, initialize_database, list_items, summary


            def _db_path(value: str | None) -> Path:
                return Path(value) if value else DEFAULT_DB


            def command_init(args: argparse.Namespace) -> int:
                path = initialize_database(_db_path(args.db), seed=not args.no_seed, reset=args.reset)
                print(f"Initialized database: {{path}}")
                return 0


            def command_add(args: argparse.Namespace) -> int:
                initialize_database(_db_path(args.db), seed=True, reset=False)
                item_id = add_item(
                    _db_path(args.db),
                    args.name,
                    category=args.category,
                    quantity=args.quantity,
                    notes=args.notes,
                )
                print(f"Added item #{{item_id}}")
                return 0


            def command_list(args: argparse.Namespace) -> int:
                initialize_database(_db_path(args.db), seed=True, reset=False)
                print(json.dumps(list_items(_db_path(args.db)), indent=2))
                return 0


            def command_summary(args: argparse.Namespace) -> int:
                initialize_database(_db_path(args.db), seed=True, reset=False)
                print(json.dumps(summary(_db_path(args.db)), indent=2))
                return 0


            def command_validate(args: argparse.Namespace) -> int:
                path = initialize_database(_db_path(args.db), seed=True, reset=args.reset)
                add_item(path, "Validation Runtime Record", category="quality", quantity=2)
                report = summary(path)
                if report["item_count"] < 4:
                    raise RuntimeError("database validation expected at least four active records")
                if report["total_quantity"] < 13:
                    raise RuntimeError("database validation expected seeded and runtime quantities")
                print(json.dumps({{"database": str(path), "summary": report}}, indent=2))
                return 0


            def build_parser() -> argparse.ArgumentParser:
                parser = argparse.ArgumentParser(description="{title} database utility")
                parser.add_argument("--db", default=str(DEFAULT_DB), help="SQLite database path.")
                subparsers = parser.add_subparsers(dest="command", required=True)

                init = subparsers.add_parser("init", help="Create schema and optional seed data.")
                init.add_argument("--reset", action="store_true", help="Delete the selected database before initializing.")
                init.add_argument("--no-seed", action="store_true", help="Create schema without seed rows.")
                init.set_defaults(func=command_init)

                add = subparsers.add_parser("add", help="Insert an inventory item.")
                add.add_argument("name")
                add.add_argument("--category", default="general")
                add.add_argument("--quantity", type=int, default=0)
                add.add_argument("--notes", default="")
                add.set_defaults(func=command_add)

                list_cmd = subparsers.add_parser("list", help="List inventory items as JSON.")
                list_cmd.set_defaults(func=command_list)

                summary_cmd = subparsers.add_parser("summary", help="Print category and total counts.")
                summary_cmd.set_defaults(func=command_summary)

                validate = subparsers.add_parser("validate", help="Run a database smoke validation.")
                validate.add_argument("--reset", action="store_true", help="Reset the selected validation database first.")
                validate.set_defaults(func=command_validate)
                return parser


            def main(argv: list[str] | None = None) -> int:
                parser = build_parser()
                args = parser.parse_args(argv)
                return int(args.func(args))


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        "tests/test_database.py": _strip(
            f"""
            from __future__ import annotations

            import sys
            import tempfile
            import unittest
            from pathlib import Path


            sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

            from {package_name}.database import add_item, initialize_database, list_items, summary


            class DatabaseTests(unittest.TestCase):
                def test_initialize_creates_seeded_database(self) -> None:
                    with tempfile.TemporaryDirectory() as tmp:
                        db_path = Path(tmp) / "test.sqlite3"
                        initialize_database(db_path, reset=True)

                        items = list_items(db_path)
                        report = summary(db_path)

                        self.assertGreaterEqual(len(items), 3)
                        self.assertGreaterEqual(report["item_count"], 3)
                        self.assertGreaterEqual(report["total_quantity"], 11)

                def test_add_item_updates_summary(self) -> None:
                    with tempfile.TemporaryDirectory() as tmp:
                        db_path = Path(tmp) / "test.sqlite3"
                        initialize_database(db_path, reset=True)
                        item_id = add_item(db_path, "New Part", category="parts", quantity=4)

                        self.assertGreater(item_id, 0)
                        names = {{item["name"] for item in list_items(db_path)}}
                        report = summary(db_path)
                        self.assertIn("New Part", names)
                        self.assertGreaterEqual(report["total_quantity"], 15)


            if __name__ == "__main__":
                unittest.main()
            """
        ),
        "build.py": _strip(
            f"""
            from __future__ import annotations

            import os
            import subprocess
            import sys
            from pathlib import Path


            ROOT = Path(__file__).resolve().parent
            PYTHONPATH = str(ROOT / "src")


            def run(command: list[str]) -> int:
                env = os.environ.copy()
                env["PYTHONPATH"] = PYTHONPATH + os.pathsep + env.get("PYTHONPATH", "")
                print("Running:", " ".join(command))
                completed = subprocess.run(command, cwd=str(ROOT), text=True, env=env)
                return completed.returncode


            def main() -> int:
                validation_db = ROOT / "data" / "validation.sqlite3"
                code = run([
                    sys.executable,
                    "-m",
                    "{package_name}.cli",
                    "--db",
                    str(validation_db),
                    "validate",
                    "--reset",
                ])
                if code != 0:
                    return code
                return run([sys.executable, "-m", "unittest", "discover", "-s", "tests"])


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        ".gitignore": _strip(
            """
            __pycache__
            *.pyc
            .venv
            data/*.sqlite3
            data/*.db
            data/*.sqlite
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            SQLite database project generated by Aegis Project Builder.

            ## What It Includes

            - `schema.sql` with metadata, inventory records, indexes, trigger, and summary view.
            - `seed.sql` with repeatable starter data.
            - `queries/report.sql` with a reusable reporting query.
            - `src/{package_name}/database.py` with connection, initialization, insert, list, and summary helpers.
            - `src/{package_name}/cli.py` with `init`, `add`, `list`, `summary`, and `validate` commands.
            - `tests/test_database.py` covering schema initialization and CRUD summary behavior.

            ## Validate

            ```powershell
            python build.py
            ```

            ## Use

            ```powershell
            $env:PYTHONPATH = "src"
            python -m {package_name}.cli init --reset
            python -m {package_name}.cli add "Example Item" --category parts --quantity 4
            python -m {package_name}.cli summary
            ```
            """
        ),
    }


def python_cli_template(project_name: str) -> dict[str, str]:
    package_name = _python_package_name(project_name)
    distribution_name = _manifest_package_name(project_name)
    title = _title_from_name(project_name)
    return {
        "pyproject.toml": _strip(
            f"""
            [build-system]
            requires = ["setuptools>=69", "wheel"]
            build-backend = "setuptools.build_meta"

            [project]
            name = "{distribution_name}"
            version = "0.1.0"
            description = "A Python CLI scaffold generated by Aegis."
            readme = "README.md"
            requires-python = ">=3.11"
            dependencies = []

            [project.optional-dependencies]
            dev = ["pytest>=8.0"]

            [project.scripts]
            {package_name} = "{package_name}.main:main"

            [tool.pytest.ini_options]
            testpaths = ["tests"]
            pythonpath = ["src"]
            """
        ),
        f"src/{package_name}/__init__.py": '__all__ = ["__version__"]\n__version__ = "0.1.0"\n',
        f"src/{package_name}/main.py": _strip(
            f"""
            from __future__ import annotations

            import argparse


            def build_parser() -> argparse.ArgumentParser:
                parser = argparse.ArgumentParser(prog="{package_name}", description="{title} command line interface")
                parser.add_argument("--name", default="Aegis", help="Name to greet.")
                return parser


            def run(name: str) -> str:
                return f"Hello, {{name}}. {title} is ready."


            def main() -> int:
                args = build_parser().parse_args()
                print(run(args.name))
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        "tests/test_smoke.py": _strip(
            f"""
            from {package_name}.main import run


            def test_run_returns_message() -> None:
                assert "Aegis" in run("Aegis")
            """
        ),
        "build.py": _strip(
            f"""
            from __future__ import annotations

            import compileall
            import importlib
            import pathlib
            import sys


            ROOT = pathlib.Path(__file__).resolve().parent
            SRC = ROOT / "src"
            TESTS = ROOT / "tests"


            def main() -> int:
                sys.path.insert(0, str(SRC))
                if not compileall.compile_dir(str(SRC), quiet=1):
                    raise SystemExit("Source compilation failed.")
                if TESTS.exists() and not compileall.compile_dir(str(TESTS), quiet=1):
                    raise SystemExit("Test compilation failed.")
                module = importlib.import_module("{package_name}.main")
                message = module.run("Aegis")
                if "Aegis" not in message:
                    raise SystemExit("Smoke check failed.")
                print("Python CLI scaffold passed validation.")
                return 0


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        ".gitignore": _strip(
            """
            .venv
            __pycache__
            .pytest_cache
            .mypy_cache
            dist
            build
            *.egg-info
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Generated by Aegis Project Builder.

            ## Setup

            ```bash
            python -m pip install -e .[dev]
            ```

            ## Run

            ```bash
            {package_name} --name Aegis
            ```

            ## Validation

            ```bash
            python build.py
            ```

            Optional pytest smoke tests are included for projects that install the `dev` extra.
            """
        ),
    }


def fastapi_template(project_name: str) -> dict[str, str]:
    package_name = _python_package_name(project_name)
    distribution_name = _manifest_package_name(project_name)
    title = _title_from_name(project_name)
    return {
        "pyproject.toml": _strip(
            f"""
            [build-system]
            requires = ["setuptools>=69", "wheel"]
            build-backend = "setuptools.build_meta"

            [project]
            name = "{distribution_name}"
            version = "0.1.0"
            description = "A FastAPI service scaffold generated by Aegis."
            readme = "README.md"
            requires-python = ">=3.11"
            dependencies = [
              "fastapi>=0.115",
              "pydantic-settings>=2.6",
              "uvicorn[standard]>=0.30"
            ]

            [project.optional-dependencies]
            dev = ["httpx>=0.27", "pytest>=8.0"]

            [tool.pytest.ini_options]
            testpaths = ["tests"]
            pythonpath = ["src"]
            """
        ),
        f"src/{package_name}/__init__.py": '__all__ = ["__version__"]\n__version__ = "0.1.0"\n',
        f"src/{package_name}/settings.py": _strip(
            f"""
            from __future__ import annotations

            from pydantic_settings import BaseSettings, SettingsConfigDict


            class Settings(BaseSettings):
                model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

                app_name: str = "{title}"
                environment: str = "development"
                api_prefix: str = "/api"


            def get_settings() -> Settings:
                return Settings()
            """
        ),
        f"src/{package_name}/main.py": _strip(
            f"""
            from __future__ import annotations

            from fastapi import FastAPI

            from .settings import get_settings


            def create_app() -> FastAPI:
                settings = get_settings()
                app = FastAPI(title=settings.app_name, version="0.1.0")

                @app.get("/health")
                async def health() -> dict[str, str]:
                    return {{"status": "ok", "service": settings.app_name, "environment": settings.environment}}

                @app.get(f"{{settings.api_prefix}}/status")
                async def api_status() -> dict[str, str]:
                    return {{"status": "ready"}}

                return app


            app = create_app()
            """
        ),
        "tests/test_health.py": _strip(
            f"""
            from fastapi.testclient import TestClient

            from {package_name}.main import create_app


            def test_health_endpoint() -> None:
                client = TestClient(create_app())
                response = client.get("/health")

                assert response.status_code == 200
                assert response.json()["status"] == "ok"
            """
        ),
        ".env.example": _strip(
            f"""
            APP_NAME="{title}"
            ENVIRONMENT=development
            API_PREFIX=/api
            """
        ),
        ".gitignore": _strip(
            """
            .venv
            __pycache__
            .pytest_cache
            .mypy_cache
            dist
            build
            *.egg-info
            .env
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            FastAPI service generated by Aegis Project Builder.

            ## Setup

            ```bash
            python -m pip install -e .[dev]
            ```

            ## Run

            ```bash
            uvicorn {package_name}.main:app --reload
            ```

            ## Validation

            ```bash
            python -m pytest
            ```
            """
        ),
    }



def python_tkinter_desktop_template(project_name: str) -> dict[str, str]:
    package_name = _python_package_name(project_name)
    distribution_name = _manifest_package_name(project_name)
    title = _title_from_name(project_name)
    return {
        "pyproject.toml": _strip(
            f"""
            [build-system]
            requires = ["setuptools>=69", "wheel"]
            build-backend = "setuptools.build_meta"

            [project]
            name = "{distribution_name}"
            version = "0.1.0"
            description = "A dependency-light Python desktop app scaffold generated by Aegis."
            readme = "README.md"
            requires-python = ">=3.11"
            dependencies = []

            [project.scripts]
            {package_name} = "{package_name}.main:main"
            """
        ),
        f"src/{package_name}/__init__.py": _strip(
            """
            __all__ = ["__version__"]
            __version__ = "0.1.0"
            """
        ),
        f"src/{package_name}/state.py": _strip(
            """
            from __future__ import annotations

            import json
            from dataclasses import asdict, dataclass
            from pathlib import Path
            from typing import Any


            @dataclass(slots=True)
            class TaskItem:
                id: int
                title: str
                done: bool = False


            class TaskStore:
                def __init__(self, items: list[TaskItem] | None = None) -> None:
                    self.items = list(items or [])

                def add(self, title: str) -> TaskItem:
                    cleaned = title.strip()
                    if not cleaned:
                        raise ValueError("title is required")
                    next_id = max((item.id for item in self.items), default=0) + 1
                    item = TaskItem(id=next_id, title=cleaned)
                    self.items.append(item)
                    return item

                def toggle(self, item_id: int) -> TaskItem:
                    for item in self.items:
                        if item.id == item_id:
                            item.done = not item.done
                            return item
                    raise KeyError(f"task not found: {item_id}")

                def remove(self, item_id: int) -> None:
                    before = len(self.items)
                    self.items = [item for item in self.items if item.id != item_id]
                    if len(self.items) == before:
                        raise KeyError(f"task not found: {item_id}")

                def remaining_count(self) -> int:
                    return sum(1 for item in self.items if not item.done)

                def to_json(self) -> list[dict[str, Any]]:
                    return [asdict(item) for item in self.items]

                @classmethod
                def from_json(cls, payload: list[dict[str, Any]]) -> "TaskStore":
                    return cls(
                        [
                            TaskItem(
                                id=int(row["id"]),
                                title=str(row["title"]),
                                done=bool(row.get("done", False)),
                            )
                            for row in payload
                        ]
                    )

                @classmethod
                def load(cls, path: Path) -> "TaskStore":
                    if not path.exists():
                        return cls()
                    payload = json.loads(path.read_text(encoding="utf-8"))
                    if not isinstance(payload, list):
                        raise ValueError("task store file must contain a list")
                    return cls.from_json(payload)

                def save(self, path: Path) -> None:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(json.dumps(self.to_json(), indent=2), encoding="utf-8")
            """
        ),
        f"src/{package_name}/app.py": _strip(
            f"""
            from __future__ import annotations

            from pathlib import Path
            import tkinter as tk
            from tkinter import messagebox, ttk

            from .state import TaskItem, TaskStore


            APP_TITLE = "{title}"
            DATA_PATH = Path(__file__).resolve().parents[2] / "data" / "tasks.json"


            class DesktopApp:
                def __init__(self, root: tk.Tk) -> None:
                    self.root = root
                    self.store = TaskStore.load(DATA_PATH)
                    self.selected_id: int | None = None

                    root.title(APP_TITLE)
                    root.geometry("720x460")
                    root.minsize(560, 360)

                    self.title_var = tk.StringVar()
                    self.status_var = tk.StringVar()

                    self._build_layout()
                    self._refresh()

                def _build_layout(self) -> None:
                    self.root.columnconfigure(0, weight=1)
                    self.root.rowconfigure(1, weight=1)

                    header = ttk.Frame(self.root, padding=(16, 14, 16, 8))
                    header.grid(row=0, column=0, sticky="ew")
                    header.columnconfigure(0, weight=1)

                    title = ttk.Label(header, text=APP_TITLE, font=("Segoe UI", 18, "bold"))
                    title.grid(row=0, column=0, sticky="w")

                    entry = ttk.Entry(header, textvariable=self.title_var)
                    entry.grid(row=1, column=0, sticky="ew", pady=(12, 0))
                    entry.bind("<Return>", lambda _event: self.add_task())

                    add_button = ttk.Button(header, text="Add", command=self.add_task)
                    add_button.grid(row=1, column=1, padx=(10, 0), pady=(12, 0))

                    body = ttk.Frame(self.root, padding=(16, 8, 16, 8))
                    body.grid(row=1, column=0, sticky="nsew")
                    body.columnconfigure(0, weight=1)
                    body.rowconfigure(0, weight=1)

                    self.listbox = tk.Listbox(body, activestyle="none", borderwidth=0, highlightthickness=1)
                    self.listbox.grid(row=0, column=0, sticky="nsew")
                    self.listbox.bind("<<ListboxSelect>>", self._on_select)

                    actions = ttk.Frame(body)
                    actions.grid(row=0, column=1, sticky="ns", padx=(12, 0))

                    ttk.Button(actions, text="Toggle", command=self.toggle_selected).grid(row=0, column=0, sticky="ew")
                    ttk.Button(actions, text="Remove", command=self.remove_selected).grid(row=1, column=0, sticky="ew", pady=(8, 0))
                    ttk.Button(actions, text="Save", command=self.save).grid(row=2, column=0, sticky="ew", pady=(8, 0))

                    footer = ttk.Label(self.root, textvariable=self.status_var, padding=(16, 8, 16, 14))
                    footer.grid(row=2, column=0, sticky="ew")

                def _on_select(self, _event: object) -> None:
                    selection = self.listbox.curselection()
                    if not selection:
                        self.selected_id = None
                        return
                    index = selection[0]
                    self.selected_id = self.store.items[index].id

                def _task_label(self, item: TaskItem) -> str:
                    mark = "[x]" if item.done else "[ ]"
                    return f"{{mark}} {{item.title}}"

                def _refresh(self) -> None:
                    self.listbox.delete(0, tk.END)
                    for item in self.store.items:
                        self.listbox.insert(tk.END, self._task_label(item))
                    remaining = self.store.remaining_count()
                    self.status_var.set(f"{{len(self.store.items)}} tasks, {{remaining}} remaining")

                def add_task(self) -> None:
                    try:
                        self.store.add(self.title_var.get())
                    except ValueError as exc:
                        messagebox.showwarning(APP_TITLE, str(exc))
                        return
                    self.title_var.set("")
                    self.save(show_message=False)
                    self._refresh()

                def toggle_selected(self) -> None:
                    if self.selected_id is None:
                        return
                    self.store.toggle(self.selected_id)
                    self.save(show_message=False)
                    self._refresh()

                def remove_selected(self) -> None:
                    if self.selected_id is None:
                        return
                    self.store.remove(self.selected_id)
                    self.selected_id = None
                    self.save(show_message=False)
                    self._refresh()

                def save(self, *, show_message: bool = True) -> None:
                    self.store.save(DATA_PATH)
                    if show_message:
                        messagebox.showinfo(APP_TITLE, f"Saved {{DATA_PATH}}")


            def run_app() -> int:
                root = tk.Tk()
                DesktopApp(root)
                root.mainloop()
                return 0
            """
        ),
        f"src/{package_name}/main.py": _strip(
            """
            from __future__ import annotations

            from .app import run_app


            def main() -> int:
                return run_app()


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        "tests/test_state.py": _strip(
            f"""
            from pathlib import Path
            import sys
            import tempfile
            import unittest

            sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

            from {package_name}.state import TaskStore


            class TaskStoreTests(unittest.TestCase):
                def test_store_add_toggle_and_remove(self) -> None:
                    store = TaskStore()
                    item = store.add("Write validation")
                    self.assertEqual(item.id, 1)
                    self.assertEqual(store.remaining_count(), 1)

                    store.toggle(item.id)
                    self.assertEqual(store.remaining_count(), 0)

                    store.remove(item.id)
                    self.assertEqual(store.items, [])

                def test_store_round_trips_json_file(self) -> None:
                    with tempfile.TemporaryDirectory() as tempdir:
                        path = Path(tempdir) / "tasks.json"
                        store = TaskStore()
                        store.add("Persist data")
                        store.save(path)

                        loaded = TaskStore.load(path)
                        self.assertEqual(loaded.to_json(), store.to_json())


            if __name__ == "__main__":
                unittest.main()
            """
        ),
        "build.py": _strip(
            """
            from __future__ import annotations

            import compileall
            import subprocess
            import sys
            from pathlib import Path


            ROOT = Path(__file__).resolve().parent


            def main() -> int:
                if not compileall.compile_dir(str(ROOT / "src"), force=True, quiet=1):
                    return 1

                command = [sys.executable, "-m", "unittest", "discover", "-s", "tests"]
                print("Running:", " ".join(command))
                return subprocess.call(command, cwd=str(ROOT))


            if __name__ == "__main__":
                raise SystemExit(main())
            """
        ),
        ".gitignore": _strip(
            """
            __pycache__
            *.pyc
            .venv
            .pytest_cache
            data/*.json
            dist
            build
            *.egg-info
            """
        ),
        "README.md": _strip(
            f"""
            # {title}

            Dependency-light Python desktop app generated by Aegis Project Builder.

            ## What It Includes

            - Tkinter GUI in `src/{package_name}/app.py`.
            - Testable task state and JSON persistence in `src/{package_name}/state.py`.
            - Unit tests that validate app logic without launching a window.
            - `build.py` that compiles source files and runs the test suite.

            ## Validate

            ```powershell
            python build.py
            ```

            ## Run

            ```powershell
            $env:PYTHONPATH = "src"
            python -m {package_name}.main
            ```
            """
        ),
    }



def _python_package_name(project_name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_]+", "_", project_name.replace("-", "_")).strip("_").lower()
    if not cleaned:
        return "aegis_app"
    if cleaned[0].isdigit():
        cleaned = f"app_{cleaned}"
    return cleaned


def _manifest_package_name(project_name: str, fallback_prefix: str = "aegis") -> str:
    cleaned = scaffold_project_name(project_name)
    if cleaned[0].isdigit():
        cleaned = f"{fallback_prefix}-{cleaned}"
    return cleaned


def _strip(value: str) -> str:
    return textwrap.dedent(value).strip() + "\n"


def _title_from_name(project_name: str) -> str:
    return scaffold_title_from_name(project_name)
